// Operational review prompts. Auditors determine applicability for each site.
export const AUDIT_CHECKLIST_TEMPLATES: Record<
  string,
  Array<[string, string?]>
> = {
  FACTORY: [
    ['Factory License', 'FACTORY_LICENSE'],
    ['Building Stability Certificate', 'BUILDING_STABILITY_CERT'],
    ['Fire Safety Certificate', 'FIRE_SAFETY_CERT'],
    ['Pollution Control Board Consent', 'PCB_CONSENT'],
    ['Hazardous Waste Authorization', 'HAZARDOUS_WASTE_AUTH'],
    ['Boiler Certificate', 'BOILER_CERTIFICATE'],
    ['Factory Plan Approval', 'FACTORY_PLAN_APPROVAL'],
    ['Annual Return (Form 21)', 'ANNUAL_RETURN_F21'],
    ['Half-Yearly Return (Form 22)', 'HALF_YEARLY_RETURN_F22'],
    ['Register of Workers', 'WORKERS_REGISTER'],
    ['Leave Register', 'LEAVE_REGISTER'],
    ['Overtime Register', 'OT_REGISTER'],
    ['Health & Safety Policy', 'HEALTH_SAFETY_POLICY'],
    ['First Aid Box', 'FIRST_AID_BOX'],
    ['Canteen License', 'CANTEEN_LICENSE'],
    ['Creche Facility (if applicable)', 'CRECHE_FACILITY'],
  ],
  SHOPS_ESTABLISHMENT: [
    ['Shops & Establishment Registration', 'SHOPS_EST_REGISTRATION'],
    ['Trade License', 'TRADE_LICENSE'],
    ['Professional Tax Registration', 'PT_REGISTRATION'],
    ['Employment Exchange Returns', 'EMPLOYMENT_EXCHANGE_RETURNS'],
    ['Register of Employees', 'EMPLOYMENT_REGISTER_F13'],
    ['Attendance Register', 'MUSTER_ROLL_REGISTER'],
    ['Wage Register', 'WAGE_REGISTER'],
    ['Leave Register', 'LEAVE_REGISTER'],
    ['Annual Return', 'ANNUAL_RETURN'],
  ],
  CONTRACTOR: [
    ['CLRA License', 'CLRA_LICENSE'],
    ['PF Registration', 'PF_REGISTRATION'],
    ['ESI Registration', 'ESI_REGISTRATION'],
    ['PF Monthly Challan', 'PF_CHALLAN'],
    ['ESI Monthly Challan', 'ESI_CHALLAN'],
    ['Professional Tax Challan', 'PT_CHALLAN'],
    ['Wage Register', 'WAGE_REGISTER'],
    ['Muster Roll / Attendance Register', 'MUSTER_ROLL_REGISTER'],
    ['Register of Fines', 'REGISTER_OF_FINES'],
    ['Register of Deductions', 'REGISTER_OF_DEDUCTIONS'],
    ['Service Certificates', 'SERVICE_CERTIFICATE'],
    ['Employment Cards', 'EMPLOYMENT_CARDS'],
    ['Wage Slips', 'WAGE_SLIPS'],
    ['Register of Employment (Form-13)', 'EMPLOYMENT_REGISTER_F13'],
    ['Bonus Register (Form C)', 'BONUS_FORM_C'],
    ['CLRA Annual Return', 'HALF_YEARLY_RETURNS_F14'],
  ],
  LABOUR_EMPLOYMENT: [
    ['Labour License', 'LABOUR_LICENSE'],
    ['Standing Orders', 'STANDING_ORDERS'],
    ['Employment Exchange Quarterly Returns', 'EMPLOYMENT_EXCHANGE_RETURNS'],
    ['Minimum Wages Register', 'MINIMUM_WAGES_RETURNS'],
    ['Equal Remuneration Register', 'EQUAL_REMUNERATION_REGISTER'],
    ['Maternity Benefit Records', 'MATERNITY_BENEFIT_RECORDS'],
    ['Gratuity Records', 'GRATUITY_RECORDS'],
    ['Industrial Disputes Records', 'INDUSTRIAL_DISPUTES_RECORDS'],
  ],
  FSSAI: [
    ['FSSAI License', 'FSSAI_LICENSE'],
    ['Food Handler Medical Certificate', 'FOOD_HANDLER_CERT'],
    ['Water Testing Report', 'WATER_TESTING_REPORT'],
    ['Pest Control Records', 'PEST_CONTROL_RECORDS'],
    ['Temperature Log (Cold Storage)', 'TEMPERATURE_LOG'],
    ['Hygiene & Sanitation Records', 'HYGIENE_SANITATION_RECORDS'],
    ['Raw Material Inspection Records', 'RAW_MATERIAL_INSPECTION'],
    ['FSSAI Annual Return', 'FSSAI_ANNUAL_RETURN'],
  ],
  PAYROLL: [
    ['PF Challan', 'PF_CHALLAN'],
    ['ESI Challan', 'ESI_CHALLAN'],
    ['Professional Tax Challan', 'PT_CHALLAN'],
    ['TDS Challan', 'TDS_CHALLAN'],
    ['Payroll Register', 'PAYROLL_REGISTER'],
    ['Salary Slips', 'WAGE_SLIPS'],
    ['Bank Statement (Salary A/c)', 'BANK_STATEMENT_SALARY'],
    ['Bonus Computation Sheet', 'BONUS_FORM_C'],
    ['Leave Encashment Records', 'LEAVE_ENCASHMENT_RECORDS'],
    ['Full & Final Settlement Records', 'FULL_FINAL_SETTLEMENT'],
  ],
  HR: [
    ['Appointment Letters', 'APPOINTMENT_LETTERS'],
    ['ID Cards Issued', 'ID_CARDS'],
    ['Employee Handbook Acknowledgement', 'EMPLOYEE_HANDBOOK'],
    ['Background Verification Records', 'BACKGROUND_VERIFICATION'],
    ['Training Records', 'TRAINING_RECORDS'],
    ['Performance Appraisal Records', 'APPRAISAL_RECORDS'],
    ['Employee Grievance Register', 'GRIEVANCE_REGISTER'],
    ['Sexual Harassment Committee (ICC) Records', 'ICC_RECORDS'],
    ['Exit Interview Records', 'EXIT_INTERVIEW_RECORDS'],
    ['Succession Planning Documents', 'SUCCESSION_PLANNING'],
  ],
  GAP: [
    ['Process Documentation', 'PROCESS_DOCUMENTATION'],
    ['SOP Compliance Check', 'SOP_COMPLIANCE'],
    ['Internal Audit Reports', 'INTERNAL_AUDIT_REPORT'],
    ['Gap Analysis Report', 'GAP_ANALYSIS_REPORT'],
    ['Corrective Action Plan', 'CORRECTIVE_ACTION_PLAN'],
    ['Risk Assessment Records', 'RISK_ASSESSMENT'],
    ['Management Review Minutes', 'MANAGEMENT_REVIEW'],
  ],
  SAFETY: [
    ['Risk assessment and hazard controls', 'RISK_ASSESSMENT'],
    [
      'Emergency exits, access routes and evacuation arrangements',
      'EMERGENCY_EVACUATION',
    ],
    ['Fire equipment access, inspection and readiness', 'FIRE_EQUIPMENT'],
    ['Machine guards and safe operating procedures', 'MACHINE_GUARDING'],
    ['Electrical installation and isolation safety', 'ELECTRICAL_SAFETY'],
    ['PPE availability, use and training', 'PPE_RECORDS'],
    ['Work permits and hazardous work controls', 'WORK_PERMITS'],
    ['Incident reporting and corrective action follow-up', 'INCIDENT_RECORDS'],
    ['First aid facilities and trained responders', 'FIRST_AID_BOX'],
    ['Housekeeping, lighting and ventilation', 'HOUSEKEEPING'],
  ],
  TRANSPORT: [
    [
      'Vehicle registration and applicable permit records',
      'VEHICLE_REGISTRATION',
    ],
    ['Vehicle fitness and inspection records', 'VEHICLE_FITNESS'],
    [
      'Vehicle insurance and pollution certificate records',
      'VEHICLE_INSURANCE',
    ],
    ['Driver licence, authorisation and training', 'DRIVER_LICENCE'],
    ['Vehicle maintenance and pre-trip checks', 'VEHICLE_MAINTENANCE'],
    ['Driver duty, rest and attendance records', 'DRIVER_DUTY_RECORDS'],
    ['Load security and passenger safety', 'LOAD_SAFETY'],
    ['Journey, gate-entry and dispatch records', 'TRIP_RECORDS'],
    ['Emergency equipment and accident reporting', 'TRANSPORT_EMERGENCY'],
  ],
  WAREHOUSE: [
    ['Applicable warehouse registrations and approvals', 'WAREHOUSE_APPROVALS'],
    ['Storage layout, stacking and rack integrity', 'STORAGE_RACK_INSPECTION'],
    [
      'Clear aisles, emergency exits and fire equipment',
      'WAREHOUSE_FIRE_SAFETY',
    ],
    ['Forklift inspection and operator training', 'FORKLIFT_INSPECTION'],
    ['Material handling and loading/unloading controls', 'MATERIAL_HANDLING'],
    ['Stock identification, traceability and rotation', 'STOCK_TRACEABILITY'],
    ['Pest control, housekeeping and sanitation', 'PEST_CONTROL_RECORDS'],
    [
      'Storage conditions and temperature monitoring where applicable',
      'STORAGE_CONDITIONS',
    ],
    ['Security, gate records and visitor controls', 'WAREHOUSE_SECURITY'],
    ['Contractor deployment and worker safety', 'WAREHOUSE_CONTRACTOR_SAFETY'],
  ],
  E_MARKETING: [
    ['Campaign approvals and ownership', 'CAMPAIGN_APPROVALS'],
    [
      'Product information and advertising claim evidence',
      'ADVERTISING_CLAIMS',
    ],
    ['Consent records and opt-out handling', 'MARKETING_CONSENT'],
    ['Customer data access and retention controls', 'CUSTOMER_DATA_CONTROLS'],
    ['Website pricing, terms and disclosures review', 'WEBSITE_DISCLOSURES'],
    ['Complaints, returns and refund communication', 'CUSTOMER_COMPLAINTS'],
    ['Vendor, agency and platform access controls', 'MARKETING_VENDOR_ACCESS'],
    [
      'Campaign performance and billing reconciliation',
      'CAMPAIGN_RECONCILIATION',
    ],
  ],
  OTHER: [
    ['Agreed audit scope and review criteria', 'AUDIT_SCOPE'],
    ['Applicable approvals and supporting evidence', 'APPLICABLE_APPROVALS'],
    ['Process controls and operating records', 'PROCESS_CONTROLS'],
    ['Risks, exceptions and corrective actions', 'CORRECTIVE_ACTION_PLAN'],
    ['Previous findings and closure evidence', 'PREVIOUS_FINDINGS'],
  ],
};
