export enum AppraisalStatus {
  DRAFT = 'DRAFT',
  INITIATED = 'INITIATED',
  SELF_PENDING = 'SELF_PENDING',
  SELF_SUBMITTED = 'SELF_SUBMITTED',
  MANAGER_PENDING = 'MANAGER_PENDING',
  MANAGER_REVIEWED = 'MANAGER_REVIEWED',
  BRANCH_PENDING = 'BRANCH_PENDING',
  BRANCH_REVIEWED = 'BRANCH_REVIEWED',
  CLIENT_PENDING = 'CLIENT_PENDING',
  CLIENT_APPROVED = 'CLIENT_APPROVED',
  SENT_BACK = 'SENT_BACK',
  REJECTED = 'REJECTED',
  CLOSED = 'CLOSED',
  LOCKED = 'LOCKED',
}

export enum AppraisalType {
  ANNUAL = 'ANNUAL',
  HALF_YEARLY = 'HALF_YEARLY',
  QUARTERLY = 'QUARTERLY',
  PROBATION_CONFIRMATION = 'PROBATION_CONFIRMATION',
  SPECIAL_REVIEW = 'SPECIAL_REVIEW',
}

export enum AppraisalRecommendation {
  CONFIRM = 'CONFIRM',
  INCREMENT = 'INCREMENT',
  PROMOTION = 'PROMOTION',
  PIP = 'PIP',
  EXTEND_PROBATION = 'EXTEND_PROBATION',
  NO_CHANGE = 'NO_CHANGE',
  SEPARATION_REVIEW = 'SEPARATION_REVIEW',
}

export enum CycleStatus {
  DRAFT = 'DRAFT',
  ACTIVE = 'ACTIVE',
  CLOSED = 'CLOSED',
  ARCHIVED = 'ARCHIVED',
}
