-- ===================================================================
-- DEPRECATED: This migration has been superseded.
-- ===================================================================
-- It was designed to transform client_assignments from a wide table
-- (crm_user_id, auditor_user_id) to a narrow table (assignment_type,
-- assigned_user_id). However, the entity was reverted to the wide
-- structure. The correct schema is now established by:
--   1. statco_schema_final.sql (creates wide-table client_assignments)
--   2. 20260207_entity_schema_reconciliation.sql (adds rotation columns)
--
-- DO NOT RUN THIS MIGRATION — it would destroy the correct schema.
-- ===================================================================
