-- Add payroll setup tab fields to persist pay-cycle, leave, attendance, and deduction preferences

BEGIN;

ALTER TABLE payroll_client_setup
  ADD COLUMN IF NOT EXISTS effective_from DATE,
  ADD COLUMN IF NOT EXISTS cycle_start_day INT NOT NULL DEFAULT 1,
  ADD COLUMN IF NOT EXISTS payout_day INT NOT NULL DEFAULT 1,
  ADD COLUMN IF NOT EXISTS lock_day INT NOT NULL DEFAULT 26,
  ADD COLUMN IF NOT EXISTS arrear_mode VARCHAR(20) NOT NULL DEFAULT 'CURRENT',
  ADD COLUMN IF NOT EXISTS leave_accrual_per_month NUMERIC(6,2) NOT NULL DEFAULT 1.50,
  ADD COLUMN IF NOT EXISTS max_carry_forward INT NOT NULL DEFAULT 30,
  ADD COLUMN IF NOT EXISTS allow_carry_forward BOOLEAN NOT NULL DEFAULT TRUE,
  ADD COLUMN IF NOT EXISTS lop_mode VARCHAR(20) NOT NULL DEFAULT 'PRORATED',
  ADD COLUMN IF NOT EXISTS attendance_source VARCHAR(20) NOT NULL DEFAULT 'MANUAL',
  ADD COLUMN IF NOT EXISTS attendance_cutoff_day INT NOT NULL DEFAULT 25,
  ADD COLUMN IF NOT EXISTS grace_minutes INT NOT NULL DEFAULT 10,
  ADD COLUMN IF NOT EXISTS auto_lock_attendance BOOLEAN NOT NULL DEFAULT TRUE,
  ADD COLUMN IF NOT EXISTS sync_enabled BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS enable_loan_recovery BOOLEAN NOT NULL DEFAULT TRUE,
  ADD COLUMN IF NOT EXISTS enable_advance_recovery BOOLEAN NOT NULL DEFAULT TRUE,
  ADD COLUMN IF NOT EXISTS default_deduction_cap_pct NUMERIC(6,2) NOT NULL DEFAULT 50.00,
  ADD COLUMN IF NOT EXISTS recovery_order VARCHAR(220) NOT NULL DEFAULT 'STATUTORY > LOAN > ADVANCE > OTHER';

COMMIT;
