/** Source identity is separate from layout identity. Never match on title or form number alone. */
export const REGISTER_SOURCES = {
  apss: {
    url: 'https://www.ricago.com/assets/front/base/file/file_management/6454.pdf',
    title: 'Code on Social Security (Andhra Pradesh) Rules, 2026',
    notification: 'G.O.Rt.No.126; Andhra Pradesh Gazette No.345, 7 July 2026',
    publicationDate: '2026-07-07',
    publisher: 'Government of Andhra Pradesh (Gazette copy hosted by Ricago)',
  },
  brss: {
    url: 'https://betastate.bihar.gov.in/file_2/FileUpload/2026/Jul/22-Jul-2026/35/DyPage/1b6711fd-9342-46c0-a9cb-7de816f3e6f5.pdf',
    title: 'Social Security (Bihar) Rules, 2026',
    notification:
      'Notification 10-01/2021 dated 30 June 2026; Bihar Gazette No.697',
    publicationDate: '2026-07-01',
    publisher: 'Government of Bihar',
  },
  uposh: {
    url: 'https://cdn.labourcodesadvisor.com/Rules/uttar-pradesh/final-osh-rules.pdf',
    title:
      'Uttar Pradesh Occupational Safety, Health and Working Conditions Rules, 2026',
    notification: '962/XXXVI-03-2026-1903305, 27 August 2026',
    publicationDate: '2026-08-27',
    publisher:
      'Government of Uttar Pradesh (Gazette copy hosted by Labour Code Advisor)',
  },
  laosh: {
    url: 'https://cdn.labourcodesadvisor.com/Rules/ladakh/final-osh-rules.pdf',
    title:
      'Ladakh Occupational Safety, Health and Working Conditions Rules, 2026',
    notification: 'S.O.238 dated 30 July 2026; SG-LD-E-02092026-1819',
    publicationDate: '2026-09-02',
    publisher:
      'Administration of Union Territory of Ladakh (Gazette copy hosted by Labour Code Advisor)',
  },
  arosh: {
    url: 'https://a4m1n.praansconsultech.com/storage/labour-code-documents/01KZG1HNEYB4P5VVA0CNZDVW64.pdf',
    title:
      'Arunachal Pradesh Occupational Safety, Health and Working Conditions Rules, 2022',
    notification: 'LAB (W) 03/2020 dated 1 April 2022; Gazette No.132',
    publicationDate: '2022-05-02',
    publisher:
      'Government of Arunachal Pradesh (Gazette copy hosted by Praans Consultech)',
  },
  gjosh: {
    url: 'https://cdn.labourcodesadvisor.com/Rules/gujarat/final-osh-rules.pdf',
    title:
      'Gujarat Occupational Safety, Health and Working Conditions Rules, 2025',
    notification:
      'GR/2025/76/FAC/142021/68396/M3 dated 6 June 2025; Gazette Extra No.87',
    publicationDate: '2025-06-12',
    publisher:
      'Government of Gujarat (Gazette copy hosted by Labour Code Advisor)',
  },
  rjosh: {
    url: 'https://employmentlaw.lkslaw.com/file/updates/legacy/rajasthan-osh-rules-2026.pdf',
    title:
      'Rajasthan Occupational Safety, Health and Working Conditions Rules, 2026',
    notification: 'S.O.23, Rajasthan Gazette, 30 June 2026',
    publicationDate: '2026-06-30',
    publisher:
      'Government of Rajasthan (Gazette copy hosted by Lakshmikumaran & Sridharan)',
  },
  brosh: {
    url: 'https://employmentlaw.lkslaw.com/file/updates/state-rules/bihar/bihar-osh-rules-2026.pdf',
    title:
      'Occupational Safety, Health and Working Conditions (Bihar) Rules, 2026',
    notification: '1/OSHC-01/2021-100 dated 30 June 2026; Gazette No.699',
    publicationDate: '2026-07-01',
    publisher:
      'Government of Bihar (Gazette copy hosted by Lakshmikumaran & Sridharan)',
  },
  aposh: {
    url: 'https://ascent-hr.com/wp-content/uploads/2026/08/OSHWC-Andhra-Pradesh-Rules-2026_07.08.2026.pdf',
    title:
      'Occupational Safety, Health and Working Conditions (Andhra Pradesh) Rules, 2026',
    notification: 'G.O.Rt.No.146 dated 6 August 2026; Gazette No.432',
    publicationDate: '2026-08-07',
    publisher:
      'Government of Andhra Pradesh (Gazette copy hosted by Ascent HR)',
  },
  arw: {
    url: 'https://a4m1n.praansconsultech.com/storage/labour-code-documents/01KZG1FS2S09AVA50JXMT95TEF.pdf',
    title: 'Code on Wages (Arunachal Pradesh) Rules, 2022',
    notification: 'LAB (W)WC/47/2019 dated 19 January 2022; Gazette No.35',
    publicationDate: '2022-02-24',
    publisher:
      'Government of Arunachal Pradesh (Gazette copy hosted by Praans Consultech)',
  },
  skw: {
    url: 'https://cdn.labourcodesadvisor.com/Rules/sikkim/final-wages-rules.pdf',
    title: 'Sikkim Code on Wages Rules, 2022',
    notification: '20/DL dated 20 April 2022; Gazette No.168',
    publicationDate: '2022-04-28',
    publisher:
      'Government of Sikkim (Gazette copy hosted by Labour Code Advisor)',
  },

  brw: {
    url: 'https://cdn.labourcodesadvisor.com/Rules/bihar/final-wages-rules.pdf',
    title: 'Code on Wages (Bihar) Rules, 2026',
    notification: 'code on wages 10-01/2021; Bihar Gazette No.696',
    publicationDate: '2026-07-01',
    publisher:
      'Government of Bihar (Gazette copy hosted by Labour Code Advisor)',
  },
  ldw: {
    url: 'https://cdn.labourcodesadvisor.com/Rules/ladakh/final-wages-rules.pdf',
    title: 'Code on Wages (Ladakh) Rules, 2026',
    notification: 'S.O.231 dated 28 July 2026; Gazette published 3 August 2026',
    publicationDate: '2026-08-03',
    publisher:
      'Government of Ladakh (Gazette copy hosted by Labour Code Advisor)',
  },
  upw: {
    url: 'https://cdn.labourcodesadvisor.com/Rules/uttar-pradesh/final-wages-rules.pdf',
    title: 'Code on Wages (Uttar Pradesh) Rules, 2026',
    notification: '1377/XXXVI-03-2026-1901341',
    publicationDate: '2026-08-12',
    publisher:
      'Government of Uttar Pradesh (Gazette copy hosted by Labour Code Advisor)',
  },

  gjw: {
    url: 'https://cdn.labourcodesadvisor.com/Rules/gujarat/final-wages-rules.pdf',
    title: 'Code on Wages (Gujarat) Rules, 2021',
    notification: 'KHR/2021/128/LVD/10/2020/555709/M(2)',
    publicationDate: '2021-10-05',
    publisher:
      'Government of Gujarat (notification copy hosted by Labour Code Advisor)',
  },
  rjw: {
    url: 'https://cdn.labourcodesadvisor.com/Rules/rajasthan/final-wages-rules.pdf',
    title: 'Code on Wages (Rajasthan) Rules, 2026',
    notification: 'S.O.40, Rajasthan Gazette',
    publicationDate: '2026-08-12',
    publisher:
      'Government of Rajasthan (Gazette copy hosted by Labour Code Advisor)',
  },
  cw: {
    url: 'https://www.labour.gov.in/static/uploads/2026/05/6eb0c35ba63b776487a025e5123b6b12.pdf',
    title: 'Wages (Central) Rules, 2026',
    notification: 'G.S.R.343(E), short title corrected by G.S.R.629(E)',
    corrigendumUrl: 'https://egazette.gov.in/WriteReadData/2026/274525.pdf',
    publicationDate: '2026-05-08',
    publisher: 'Ministry of Labour and Employment',
  },
  osh: {
    url: 'https://www.labour.gov.in/static/uploads/2026/05/ee246f790cad0b8e99c3828f34fa09a6.pdf',
    title:
      'Occupational Safety, Health and Working Conditions (Central) Rules, 2026',
    notification: 'G.S.R.345(E)',
    publicationDate: '2026-05-08',
    publisher: 'Ministry of Labour and Employment',
  },
  ss: {
    url: 'https://www.labour.gov.in/static/uploads/2026/05/49aa9b62c2125499c37399b90e969d67.pdf',
    title: 'Code on Social Security (Central) Rules, 2026',
    notification: 'G.S.R.344(E)',
    publicationDate: '2026-05-08',
    publisher: 'Ministry of Labour and Employment',
  },
  ir: {
    url: 'https://www.labour.gov.in/static/uploads/2026/05/f05a2c220dcdec0ea9c55e84d9ff791f.pdf',
    title: 'Industrial Relations (Central) Rules, 2026',
    notification: 'G.S.R.342(E)',
    publicationDate: '2026-05-08',
    publisher: 'Ministry of Labour and Employment',
  },
  apw: {
    url: 'https://www.ricago.com/assets/front/base/file/file_management/6536.pdf',
    title: 'Code on Wages (Andhra Pradesh) Rules, 2026',
    notification: 'G.O.Rt.No.124; Gazette No.328',
    publicationDate: '2026-06-29',
    publisher: 'Government of Andhra Pradesh (Gazette copy hosted by Ricago)',
  },
  tsi: {
    url: 'https://ipass.telangana.gov.in/viewpdf.aspx?filepathnew=D%3A%2FTS-iPASSFinal%2Fdocs%2F2019LETF_MS6+%282%29.PDF',
    title: 'Telangana integrated registers order, 2019',
    notification: 'G.O.Ms.No.6',
    publicationDate: '2019-03-02',
    publisher: 'Government of Telangana',
  },
  mh: {
    url: 'https://mahakamgar.maharashtra.gov.in/Site/Upload/PDF/Regulation_of_Employment_Conditions_of_Service_Rules_2018.pdf',
    title:
      'Maharashtra Shops and Establishments (Regulation of Employment and Conditions of Service) Rules, 2018',
    notification: 'Gazette, 23 March 2018',
    publicationDate: '2018-03-23',
    publisher: 'Government of Maharashtra',
  },
  tn: {
    url: 'https://dish.tn.gov.in/assets/pdf/Amendment%20of%20Rules%20for%20Maintenance%20of%20registers.pdf',
    title: 'Tamil Nadu Factories Rules amendment, 2021',
    notification: 'Tamil Nadu Government Gazette, 24 March 2021',
    publicationDate: '2021-03-24',
    publisher: 'Government of Tamil Nadu',
  },
  clra: {
    url: 'https://clc.gov.in/clc/acts-rules/contract-labour-regulation-abolition-act-1970',
    title: 'Contract Labour (Regulation and Abolition) Central Rules, 1971',
    notification: 'Legacy rules, subject to repeal and savings',
    publicationDate: null,
    publisher: 'Chief Labour Commissioner (Central)',
  },
} as const;

export const REGISTER_FORMS = [
  {
    id: 'ap--social-security-2020--ap-ss-2026--xx--apss',
    jurisdiction: 'AP',
    actCode: 'SOCIAL_SECURITY_2020',
    rulesCode: 'AP_SS_2026',
    formNumber: 'XX',
    title: 'Women employees register',
    ruleReference: 'Rule 28(1)(a)(iv)',
    kind: 'REGISTER',
    sourceId: 'apss',
    sourceStatus: 'FINAL',
    sourcePage: 73,
    layoutId: null,
    notes:
      'Rule 1(2) commences on Gazette publication. Women employee and maternity records require authorised HR evidence, not payroll inference. Rule 28(1)(a)(iv) prescribes this form; preserve originals for five calendar years from last entry under Rule 28(1)(e). Entries: English and Hindi or the language understood by the majority. Common Wages/OSH registers mentioned in Rule 28 retain their own legal identities; this women register is not a substitute. Monthly snapshots require supporting prior history.',
    verifiedOn: '2026-09-14',
    effectiveFrom: '2026-07-07',
    applicability: 'REVIEW_REQUIRED',
    generation: 'REFERENCE_ONLY',
  },
  {
    id: 'br--social-security-2020--bihar-ss-2026--xxi--brss',
    jurisdiction: 'BR',
    actCode: 'SOCIAL_SECURITY_2020',
    rulesCode: 'BIHAR_SS_2026',
    formNumber: 'XXI',
    title: 'Women employees register',
    ruleReference: 'Rule 27(1)(a)(iv)',
    kind: 'REGISTER',
    sourceId: 'brss',
    sourceStatus: 'FINAL',
    sourcePage: 106,
    layoutId: null,
    notes:
      'Rule 1(3) commences on Gazette publication. Women employee and maternity records require authorised HR evidence, not payroll inference. Rule 27(1)(a)(iv) prescribes this form; preserve originals for five calendar years from last entry under Rule 27(1)(e). Entries: English and Hindi or the language understood by the majority. Common Wages/OSH registers mentioned in Rule 27 retain their own legal identities; this women register is not a substitute. Monthly snapshots require supporting prior history.',
    verifiedOn: '2026-09-14',
    effectiveFrom: '2026-07-01',
    applicability: 'REVIEW_REQUIRED',
    generation: 'REFERENCE_ONLY',
  },
  {
    id: 'up--osh-2020--uttar-pradesh-osh-2026--6--uposh',
    jurisdiction: 'UP',
    actCode: 'OSH_2020',
    rulesCode: 'UTTAR_PRADESH_OSH_2026',
    formNumber: '6',
    title: 'Attendance register',
    ruleReference: 'Rules 10(1), 59(3), 59(5)',
    kind: 'REGISTER',
    sourceId: 'uposh',
    sourceStatus: 'FINAL',
    sourcePage: 477,
    layoutId: 'up-osh-6',
    notes:
      'Effective on Gazette publication, 27 August 2026. Rule 55 requires original records for five calendar years and preservation through disposal/execution of pending proceedings; manual records use Hindi/English or a language understood by most workers. Requires work/rest schedule, relay rotation and a separate adolescent register. Repeated day labels in the printed schedule need reviewed interpretation; preparation pending.',
    verifiedOn: '2026-09-14',
    effectiveFrom: '2026-08-27',
    applicability: 'REVIEW_REQUIRED',
    generation: 'REFERENCE_ONLY',
  },
  {
    id: 'up--osh-2020--uttar-pradesh-osh-2026--14--uposh',
    jurisdiction: 'UP',
    actCode: 'OSH_2020',
    rulesCode: 'UTTAR_PRADESH_OSH_2026',
    formNumber: '14',
    title: 'Worker leave book',
    ruleReference: 'Rule 56(1)',
    kind: 'CARD',
    sourceId: 'uposh',
    sourceStatus: 'FINAL',
    sourcePage: 490,
    layoutId: 'up-osh-14',
    notes:
      'Effective on Gazette publication, 27 August 2026. Rule 55 requires original records for five calendar years and preservation through disposal/execution of pending proceedings; manual records use Hindi/English or a language understood by most workers. Worker-owned leave book. Employer may retain for entries for no more than one week; calendar-year balances require a dedicated ledger. Preparation pending.',
    verifiedOn: '2026-09-14',
    effectiveFrom: '2026-08-27',
    applicability: 'REVIEW_REQUIRED',
    generation: 'REFERENCE_ONLY',
  },
  {
    id: 'up--osh-2020--uttar-pradesh-osh-2026--15--uposh',
    jurisdiction: 'UP',
    actCode: 'OSH_2020',
    rulesCode: 'UTTAR_PRADESH_OSH_2026',
    formNumber: '15',
    title: 'Leave with wages register',
    ruleReference: 'Rule 57',
    kind: 'REGISTER',
    sourceId: 'uposh',
    sourceStatus: 'FINAL',
    sourcePage: 491,
    layoutId: 'up-osh-15',
    notes:
      'Effective on Gazette publication, 27 August 2026. Rule 55 requires original records for five calendar years and preservation through disposal/execution of pending proceedings; manual records use Hindi/English or a language understood by most workers. Update weekly, fortnightly or at least monthly using calendar-year worked/lay-off/maternity/leave totals and carry-forward balances. Preparation pending; monthly applications alone cannot establish these balances.',
    verifiedOn: '2026-09-14',
    effectiveFrom: '2026-08-27',
    applicability: 'REVIEW_REQUIRED',
    generation: 'REFERENCE_ONLY',
  },
  {
    id: 'up--osh-2020--uttar-pradesh-osh-2026--16--uposh',
    jurisdiction: 'UP',
    actCode: 'OSH_2020',
    rulesCode: 'UTTAR_PRADESH_OSH_2026',
    formNumber: '16',
    title: 'Accidents and dangerous occurrences',
    ruleReference: 'Rule 60',
    kind: 'REGISTER',
    sourceId: 'uposh',
    sourceStatus: 'FINAL',
    sourcePage: 492,
    layoutId: 'up-osh-16',
    notes:
      'Effective on Gazette publication, 27 August 2026. Rule 55 requires original records for five calendar years and preservation through disposal/execution of pending proceedings; manual records use Hindi/English or a language understood by most workers. Retains all 20 numbered groups including reporting time, injured-person details, shift, cause, notice authentication, witnesses and insurance local office. Incident/report evidence is mandatory. No days-absent or man-hours field is prescribed in this form.',
    verifiedOn: '2026-09-14',
    effectiveFrom: '2026-08-27',
    applicability: 'REVIEW_REQUIRED',
    generation: 'REFERENCE_ONLY',
  },
  {
    id: 'up--osh-2020--uttar-pradesh-osh-2026--29--uposh',
    jurisdiction: 'UP',
    actCode: 'OSH_2020',
    rulesCode: 'UTTAR_PRADESH_OSH_2026',
    formNumber: '29',
    title: 'Register of contractors maintained by designated authority',
    ruleReference: 'Rule 81',
    kind: 'AUTHORITY_REGISTER',
    sourceId: 'uposh',
    sourceStatus: 'FINAL',
    sourcePage: 511,
    layoutId: 'up-osh-29',
    notes:
      'Effective on Gazette publication, 27 August 2026. Rule 55 requires original records for five calendar years and preservation through disposal/execution of pending proceedings; manual records use Hindi/English or a language understood by most workers. Maintained electronically by the designated licensing authority, not by the employer. Reference only.',
    verifiedOn: '2026-09-14',
    effectiveFrom: '2026-08-27',
    applicability: 'REVIEW_REQUIRED',
    generation: 'REFERENCE_ONLY',
  },
  {
    id: 'la--osh-2020--ladakh-osh-2026--i--laosh',
    jurisdiction: 'LA',
    actCode: 'OSH_2020',
    rulesCode: 'LADAKH_OSH_2026',
    formNumber: 'I',
    title: 'Employee register prescribed under Ladakh Wages Rules',
    ruleReference: 'Rule 39 (Wages Form I)',
    kind: 'REGISTER',
    sourceId: 'laosh',
    sourceStatus: 'FINAL',
    sourcePage: 23,
    layoutId: 'la-osh-i',
    notes:
      'Gazette publication is 2 September 2026; the notification date is 30 July. Preparation conservatively starts with the first full month after publication; no retrospective version is inferred from the Code-linked commencement clause. Rule 39 expressly uses the employee register prescribed by Ladakh Wages Rules. Form I identifies that referenced Wages schedule, not a separate OSH schedule. Review approved Wages records before generating a duplicate.',
    verifiedOn: '2026-09-14',
    effectiveFrom: '2026-09-02',
    applicability: 'REVIEW_REQUIRED',
    generation: 'REFERENCE_ONLY',
  },
  {
    id: 'la--osh-2020--ladakh-osh-2026--iv--laosh',
    jurisdiction: 'LA',
    actCode: 'OSH_2020',
    rulesCode: 'LADAKH_OSH_2026',
    formNumber: 'IV',
    title: 'Wage register prescribed under Ladakh Wages Rules',
    ruleReference: 'Rule 45 (Wages Form IV)',
    kind: 'REGISTER',
    sourceId: 'laosh',
    sourceStatus: 'FINAL',
    sourcePage: 25,
    layoutId: 'la-osh-iv',
    notes:
      'Gazette publication is 2 September 2026; the notification date is 30 July. Preparation conservatively starts with the first full month after publication; no retrospective version is inferred from the Code-linked commencement clause. Rule 45 refers to the register prescribed under the appropriate-government Wages rules. Under this Ladakh-scoped preparation, Form IV identifies the Ladakh Wages schedule; do not substitute a Central form.',
    verifiedOn: '2026-09-14',
    effectiveFrom: '2026-09-02',
    applicability: 'REVIEW_REQUIRED',
    generation: 'REFERENCE_ONLY',
  },
  {
    id: 'la--osh-2020--ladakh-osh-2026--16--laosh',
    jurisdiction: 'LA',
    actCode: 'OSH_2020',
    rulesCode: 'LADAKH_OSH_2026',
    formNumber: '16',
    title: 'Muster roll and overtime',
    ruleReference: 'Rules 34, 41(1)(a), 44(1)',
    kind: 'REGISTER',
    sourceId: 'laosh',
    sourceStatus: 'FINAL',
    sourcePage: 204,
    layoutId: 'la-osh-16',
    notes:
      'Gazette publication is 2 September 2026; the notification date is 30 July. Preparation conservatively starts with the first full month after publication; no retrospective version is inferred from the Code-linked commencement clause. Daily and weekly overtime, weekly rest lost under exemption orders and compensatory holidays require their own evidence. Layout preparation pending.',
    verifiedOn: '2026-09-14',
    effectiveFrom: '2026-09-02',
    applicability: 'REVIEW_REQUIRED',
    generation: 'REFERENCE_ONLY',
  },
  {
    id: 'la--osh-2020--ladakh-osh-2026--17--laosh',
    jurisdiction: 'LA',
    actCode: 'OSH_2020',
    rulesCode: 'LADAKH_OSH_2026',
    formNumber: '17',
    title: 'Worker attendance card',
    ruleReference: 'Rule 41(2)(a)',
    kind: 'CARD',
    sourceId: 'laosh',
    sourceStatus: 'FINAL',
    sourcePage: 205,
    layoutId: 'la-osh-17',
    notes:
      'Gazette publication is 2 September 2026; the notification date is 30 July. Preparation conservatively starts with the first full month after publication; no retrospective version is inferred from the Code-linked commencement clause. The card remains with the worker. The biometric-system exception requires all eight conditions in Rule 41(2); device usage alone does not establish exemption. Layout preparation pending.',
    verifiedOn: '2026-09-14',
    effectiveFrom: '2026-09-02',
    applicability: 'REVIEW_REQUIRED',
    generation: 'REFERENCE_ONLY',
  },
  {
    id: 'la--osh-2020--ladakh-osh-2026--18--laosh',
    jurisdiction: 'LA',
    actCode: 'OSH_2020',
    rulesCode: 'LADAKH_OSH_2026',
    formNumber: '18',
    title: 'Accidents and dangerous occurrences',
    ruleReference: 'Rule 42',
    kind: 'REGISTER',
    sourceId: 'laosh',
    sourceStatus: 'FINAL',
    sourcePage: 206,
    layoutId: 'la-osh-18',
    notes:
      'Gazette publication is 2 September 2026; the notification date is 30 July. Preparation conservatively starts with the first full month after publication; no retrospective version is inferred from the Code-linked commencement clause. Records total man-hours lost, not days absent. Incident/report evidence is required; do not infer events or hours from payroll.',
    verifiedOn: '2026-09-14',
    effectiveFrom: '2026-09-02',
    applicability: 'REVIEW_REQUIRED',
    generation: 'REFERENCE_ONLY',
  },
  {
    id: 'la--osh-2020--ladakh-osh-2026--19--laosh',
    jurisdiction: 'LA',
    actCode: 'OSH_2020',
    rulesCode: 'LADAKH_OSH_2026',
    formNumber: '19',
    title: 'Leave with wages register',
    ruleReference: 'Rule 43(1)',
    kind: 'REGISTER',
    sourceId: 'laosh',
    sourceStatus: 'FINAL',
    sourcePage: 207,
    layoutId: 'la-osh-19',
    notes:
      'Gazette publication is 2 September 2026; the notification date is 30 July. Preparation conservatively starts with the first full month after publication; no retrospective version is inferred from the Code-linked commencement clause. Annual calendar-year ledger with monthly worked-day totals, earned leave, opening balance, use, encashment and closing balance. Annual preparation uses reviewed full-year HR records and reconciles worked days and balances; it does not calculate entitlement. Columns 7+8 establish available credit before the uses in columns 10+11; column 12 is the remaining balance. The full-year flow does not cover a transition year spanning different rule versions. Retain for three years after the last entry.',
    verifiedOn: '2026-09-14',
    effectiveFrom: '2026-09-02',
    applicability: 'REVIEW_REQUIRED',
    generation: 'REFERENCE_ONLY',
  },
  {
    id: 'la--osh-2020--ladakh-osh-2026--29--laosh',
    jurisdiction: 'LA',
    actCode: 'OSH_2020',
    rulesCode: 'LADAKH_OSH_2026',
    formNumber: '29',
    title: 'Register of contractors maintained by designated authority',
    ruleReference: 'Rule 67',
    kind: 'AUTHORITY_REGISTER',
    sourceId: 'laosh',
    sourceStatus: 'FINAL',
    sourcePage: 218,
    layoutId: 'la-osh-29',
    notes:
      'Gazette publication is 2 September 2026; the notification date is 30 July. Preparation conservatively starts with the first full month after publication; no retrospective version is inferred from the Code-linked commencement clause. Maintained by the designated licensing authority, not the employer. Reference only.',
    verifiedOn: '2026-09-14',
    effectiveFrom: '2026-09-02',
    applicability: 'REVIEW_REQUIRED',
    generation: 'REFERENCE_ONLY',
  },
  {
    id: 'ar--osh-2020--arunachal-pradesh-osh-2022--viii--arosh',
    jurisdiction: 'AR',
    actCode: 'OSH_2020',
    rulesCode: 'ARUNACHAL_PRADESH_OSH_2022',
    formNumber: 'VIII',
    title: 'Register of workers, wages, overtime, fine and deductions',
    ruleReference: 'Rule 21(a); schedule cites 21(1)',
    kind: 'REGISTER',
    sourceId: 'arosh',
    sourceStatus: 'FINAL',
    sourcePage: 207,
    layoutId: 'ar-osh-viii',
    notes:
      'Commencement follows the parent Code: S.O.5321(E), 21 November 2025. Verify appropriate-government jurisdiction and retain the prescribed authentication/language evidence. Rule 21 and its schedule contain inconsistent sub-rule numbering; both references are retained. General records require one-year retention; leave records require two years and proper transfer before destruction.',
    verifiedOn: '2026-09-14',
    effectiveFrom: '2025-11-21',
    applicability: 'REVIEW_REQUIRED',
    generation: 'REFERENCE_ONLY',
  },
  {
    id: 'ar--osh-2020--arunachal-pradesh-osh-2022--x--arosh',
    jurisdiction: 'AR',
    actCode: 'OSH_2020',
    rulesCode: 'ARUNACHAL_PRADESH_OSH_2022',
    formNumber: 'X',
    title: 'Register of accidents and dangerous occurrences',
    ruleReference: 'Rule 21(3); schedule cites 21(4)',
    kind: 'REGISTER',
    sourceId: 'arosh',
    sourceStatus: 'FINAL',
    sourcePage: 214,
    layoutId: 'ar-osh-x',
    notes:
      'Commencement follows the parent Code: S.O.5321(E), 21 November 2025. Verify appropriate-government jurisdiction and retain the prescribed authentication/language evidence. Rule 21 and its schedule contain inconsistent sub-rule numbering; both references are retained. General records require one-year retention; leave records require two years and proper transfer before destruction.',
    verifiedOn: '2026-09-14',
    effectiveFrom: '2025-11-21',
    applicability: 'REVIEW_REQUIRED',
    generation: 'REFERENCE_ONLY',
  },
  {
    id: 'ar--osh-2020--arunachal-pradesh-osh-2022--xi--arosh',
    jurisdiction: 'AR',
    actCode: 'OSH_2020',
    rulesCode: 'ARUNACHAL_PRADESH_OSH_2022',
    formNumber: 'XI',
    title: 'Register for leave with wages',
    ruleReference: 'Rule 21(4); schedule cites 21(5)',
    kind: 'REGISTER',
    sourceId: 'arosh',
    sourceStatus: 'FINAL',
    sourcePage: 214,
    layoutId: 'ar-osh-xi',
    notes:
      'Commencement follows the parent Code: S.O.5321(E), 21 November 2025. Verify appropriate-government jurisdiction and retain the prescribed authentication/language evidence. Rule 21 and its schedule contain inconsistent sub-rule numbering; both references are retained. General records require one-year retention; leave records require two years and proper transfer before destruction.',
    verifiedOn: '2026-09-14',
    effectiveFrom: '2025-11-21',
    applicability: 'REVIEW_REQUIRED',
    generation: 'REFERENCE_ONLY',
  },
  {
    id: 'gj--osh-2020--gujarat-osh-2025--13--gjosh',
    jurisdiction: 'GJ',
    actCode: 'OSH_2020',
    rulesCode: 'GUJARAT_OSH_2025',
    formNumber: '13',
    title: 'Register of workers, wages, overtime, fine and deductions',
    ruleReference: 'Rule 29(1)(a) and 38(3)',
    kind: 'REGISTER',
    sourceId: 'gjosh',
    sourceStatus: 'FINAL',
    sourcePage: 61,
    layoutId: 'gj-osh-13',
    notes:
      'Commencement follows the parent Code: S.O.5321(E), 21 November 2025. Verify appropriate-government jurisdiction and retain the prescribed authentication/language evidence. Rules 29/38 prescribe language and original-record retention. The December 2025 amendment source inspected is a draft and is not used as an operative schedule.',
    verifiedOn: '2026-09-14',
    effectiveFrom: '2025-11-21',
    applicability: 'REVIEW_REQUIRED',
    generation: 'REFERENCE_ONLY',
  },
  {
    id: 'gj--osh-2020--gujarat-osh-2025--22--gjosh',
    jurisdiction: 'GJ',
    actCode: 'OSH_2020',
    rulesCode: 'GUJARAT_OSH_2025',
    formNumber: '22',
    title: 'Register of accidents, major accidents and dangerous occurrences',
    ruleReference: 'Rule 36',
    kind: 'REGISTER',
    sourceId: 'gjosh',
    sourceStatus: 'FINAL',
    sourcePage: 66,
    layoutId: 'gj-osh-22',
    notes:
      'Commencement follows the parent Code: S.O.5321(E), 21 November 2025. Verify appropriate-government jurisdiction and retain the prescribed authentication/language evidence. Rules 29/38 prescribe language and original-record retention. The December 2025 amendment source inspected is a draft and is not used as an operative schedule. Rule 36 is limited to factories or building/other construction work; verified branch facts must establish this usage. Absence days include holidays and off days.',
    verifiedOn: '2026-09-14',
    effectiveFrom: '2025-11-21',
    applicability: 'REVIEW_REQUIRED',
    generation: 'REFERENCE_ONLY',
  },
  {
    id: 'rj--osh-2020--rajasthan-osh-2026--16--rjosh',
    jurisdiction: 'RJ',
    actCode: 'OSH_2020',
    rulesCode: 'RAJASTHAN_OSH_2026',
    formNumber: '16',
    title: 'Register of employees',
    ruleReference: 'Rule 49(1)(a)',
    kind: 'REGISTER',
    sourceId: 'rjosh',
    sourceStatus: 'FINAL',
    sourcePage: 186,
    layoutId: 'rj-osh-16',
    notes:
      'Rule 1(3): effective from Gazette publication. Rule 49 requires original registers for five calendar years after the last entry; check language and authentication requirements. Rule 49(3) permits corresponding Wages records to satisfy this requirement after applicability and scope review.',
    verifiedOn: '2026-09-14',
    effectiveFrom: '2026-06-30',
    applicability: 'REVIEW_REQUIRED',
    generation: 'REFERENCE_ONLY',
  },
  {
    id: 'rj--osh-2020--rajasthan-osh-2026--17--rjosh',
    jurisdiction: 'RJ',
    actCode: 'OSH_2020',
    rulesCode: 'RAJASTHAN_OSH_2026',
    formNumber: '17',
    title: 'Attendance muster roll register',
    ruleReference: 'Rule 49(1)(b)',
    kind: 'REGISTER',
    sourceId: 'rjosh',
    sourceStatus: 'FINAL',
    sourcePage: 188,
    layoutId: 'rj-osh-17',
    notes:
      'Rule 1(3): effective from Gazette publication. Rule 49 requires original registers for five calendar years after the last entry; check language and authentication requirements. Rule 49(3) permits corresponding Wages records to satisfy this requirement after applicability and scope review.',
    verifiedOn: '2026-09-14',
    effectiveFrom: '2026-06-30',
    applicability: 'REVIEW_REQUIRED',
    generation: 'REFERENCE_ONLY',
  },
  {
    id: 'rj--osh-2020--rajasthan-osh-2026--18--rjosh',
    jurisdiction: 'RJ',
    actCode: 'OSH_2020',
    rulesCode: 'RAJASTHAN_OSH_2026',
    formNumber: '18',
    title: 'Register for wages, overtime and deductions',
    ruleReference: 'Rule 49(1)(c)',
    kind: 'REGISTER',
    sourceId: 'rjosh',
    sourceStatus: 'FINAL',
    sourcePage: 189,
    layoutId: 'rj-osh-18',
    notes:
      'Rule 1(3): effective from Gazette publication. Rule 49 requires original registers for five calendar years after the last entry; check language and authentication requirements. Rule 49(3) permits corresponding Wages records to satisfy this requirement after applicability and scope review.',
    verifiedOn: '2026-09-14',
    effectiveFrom: '2026-06-30',
    applicability: 'REVIEW_REQUIRED',
    generation: 'REFERENCE_ONLY',
  },
  {
    id: 'rj--osh-2020--rajasthan-osh-2026--19--rjosh',
    jurisdiction: 'RJ',
    actCode: 'OSH_2020',
    rulesCode: 'RAJASTHAN_OSH_2026',
    formNumber: '19',
    title: 'Register of leave with wages',
    ruleReference: 'Rule 49(1)(d) and 53',
    kind: 'REGISTER',
    sourceId: 'rjosh',
    sourceStatus: 'FINAL',
    sourcePage: 190,
    layoutId: 'rj-osh-19',
    notes:
      'Rule 1(3): effective from Gazette publication. Rule 49 requires original registers for five calendar years after the last entry; check language and authentication requirements.',
    verifiedOn: '2026-09-14',
    effectiveFrom: '2026-06-30',
    applicability: 'REVIEW_REQUIRED',
    generation: 'REFERENCE_ONLY',
  },
  {
    id: 'rj--osh-2020--rajasthan-osh-2026--20--rjosh',
    jurisdiction: 'RJ',
    actCode: 'OSH_2020',
    rulesCode: 'RAJASTHAN_OSH_2026',
    formNumber: '20',
    title: 'Wage slip',
    ruleReference: 'Rule 49(2)',
    kind: 'WAGE_SLIP',
    sourceId: 'rjosh',
    sourceStatus: 'FINAL',
    sourcePage: 191,
    layoutId: 'rj-osh-20',
    notes:
      'Rule 1(3): effective from Gazette publication. Rule 49 requires original registers for five calendar years after the last entry; check language and authentication requirements. Rule 49(3) permits corresponding Wages records to satisfy this requirement after applicability and scope review.',
    verifiedOn: '2026-09-14',
    effectiveFrom: '2026-06-30',
    applicability: 'REVIEW_REQUIRED',
    generation: 'REFERENCE_ONLY',
  },
  {
    id: 'rj--osh-2020--rajasthan-osh-2026--24--rjosh',
    jurisdiction: 'RJ',
    actCode: 'OSH_2020',
    rulesCode: 'RAJASTHAN_OSH_2026',
    formNumber: '24',
    title: 'Register of accidents and dangerous occurrences',
    ruleReference: 'Rule 52',
    kind: 'REGISTER',
    sourceId: 'rjosh',
    sourceStatus: 'FINAL',
    sourcePage: 198,
    layoutId: 'rj-osh-24',
    notes:
      'Rule 1(3): effective from Gazette publication. Rule 49 requires original registers for five calendar years after the last entry; check language and authentication requirements.',
    verifiedOn: '2026-09-14',
    effectiveFrom: '2026-06-30',
    applicability: 'REVIEW_REQUIRED',
    generation: 'REFERENCE_ONLY',
  },
  {
    id: 'br--osh-2020--bihar-osh-2026--viii--brosh',
    jurisdiction: 'BR',
    actCode: 'OSH_2020',
    rulesCode: 'BIHAR_OSH_2026',
    formNumber: 'VIII',
    title: 'Employee register',
    ruleReference: 'Rule 27',
    kind: 'REGISTER',
    sourceId: 'brosh',
    sourceStatus: 'FINAL',
    sourcePage: 381,
    layoutId: 'br-osh-viii',
    notes:
      'Rule 1(3): effective from Gazette publication. Entries in English or Hindi; preserve originals for five calendar years after the last entry. Rule 27(2) recognises corresponding registers required under the Wages and Social Security Codes; review approved Wages records before preparing duplicates.',
    verifiedOn: '2026-09-14',
    effectiveFrom: '2026-07-01',
    applicability: 'REVIEW_REQUIRED',
    generation: 'REFERENCE_ONLY',
  },
  {
    id: 'br--osh-2020--bihar-osh-2026--viii-a--brosh',
    jurisdiction: 'BR',
    actCode: 'OSH_2020',
    rulesCode: 'BIHAR_OSH_2026',
    formNumber: 'VIII(A)',
    title: 'Attendance register-cum-muster roll',
    ruleReference: 'Rule 27',
    kind: 'REGISTER',
    sourceId: 'brosh',
    sourceStatus: 'FINAL',
    sourcePage: 382,
    layoutId: 'br-osh-viii-a',
    notes:
      'Rule 1(3): effective from Gazette publication. Entries in English or Hindi; preserve originals for five calendar years after the last entry. Rule 27(2) recognises corresponding registers required under the Wages and Social Security Codes; review approved Wages records before preparing duplicates.',
    verifiedOn: '2026-09-14',
    effectiveFrom: '2026-07-01',
    applicability: 'REVIEW_REQUIRED',
    generation: 'REFERENCE_ONLY',
  },
  {
    id: 'br--osh-2020--bihar-osh-2026--viii-b--brosh',
    jurisdiction: 'BR',
    actCode: 'OSH_2020',
    rulesCode: 'BIHAR_OSH_2026',
    formNumber: 'VIII(B)',
    title: 'Register for wages, overtime and deductions',
    ruleReference: 'Rule 27',
    kind: 'REGISTER',
    sourceId: 'brosh',
    sourceStatus: 'FINAL',
    sourcePage: 383,
    layoutId: 'br-osh-viii-b',
    notes:
      'Rule 1(3): effective from Gazette publication. Entries in English or Hindi; preserve originals for five calendar years after the last entry. Rule 27(2) recognises corresponding registers required under the Wages and Social Security Codes; review approved Wages records before preparing duplicates.',
    verifiedOn: '2026-09-14',
    effectiveFrom: '2026-07-01',
    applicability: 'REVIEW_REQUIRED',
    generation: 'REFERENCE_ONLY',
  },
  {
    id: 'br--osh-2020--bihar-osh-2026--viii-c--brosh',
    jurisdiction: 'BR',
    actCode: 'OSH_2020',
    rulesCode: 'BIHAR_OSH_2026',
    formNumber: 'VIII(C)',
    title: 'Wage slip',
    ruleReference: 'Rule 27',
    kind: 'WAGE_SLIP',
    sourceId: 'brosh',
    sourceStatus: 'FINAL',
    sourcePage: 384,
    layoutId: 'br-osh-viii-c',
    notes:
      'Rule 1(3): effective from Gazette publication. Entries in English or Hindi; preserve originals for five calendar years after the last entry. Rule 27(2) recognises corresponding registers required under the Wages and Social Security Codes; review approved Wages records before preparing duplicates.',
    verifiedOn: '2026-09-14',
    effectiveFrom: '2026-07-01',
    applicability: 'REVIEW_REQUIRED',
    generation: 'REFERENCE_ONLY',
  },
  {
    id: 'br--osh-2020--bihar-osh-2026--x--brosh',
    jurisdiction: 'BR',
    actCode: 'OSH_2020',
    rulesCode: 'BIHAR_OSH_2026',
    formNumber: 'X',
    title: 'Register of accidents and dangerous occurrences',
    ruleReference: 'Rule 30',
    kind: 'REGISTER',
    sourceId: 'brosh',
    sourceStatus: 'FINAL',
    sourcePage: 388,
    layoutId: 'br-osh-x',
    notes:
      'Rule 1(3): effective from Gazette publication. Entries in English or Hindi; preserve originals for five calendar years after the last entry. Rule 30 requires quarterly electronic communication to the Inspector-cum-Facilitator; preparation here does not submit the register.',
    verifiedOn: '2026-09-14',
    effectiveFrom: '2026-07-01',
    applicability: 'REVIEW_REQUIRED',
    generation: 'REFERENCE_ONLY',
  },
  {
    id: 'br--osh-2020--bihar-osh-2026--xi--brosh',
    jurisdiction: 'BR',
    actCode: 'OSH_2020',
    rulesCode: 'BIHAR_OSH_2026',
    formNumber: 'XI',
    title: 'Register for leave with wages',
    ruleReference: 'Rule 31(1)',
    kind: 'REGISTER',
    sourceId: 'brosh',
    sourceStatus: 'FINAL',
    sourcePage: 388,
    layoutId: 'br-osh-xi',
    notes:
      'Rule 1(3): effective from Gazette publication. Entries in English or Hindi; preserve originals for five calendar years after the last entry. Rule 31 requires proper transfer to a new register before destruction even after five years.',
    verifiedOn: '2026-09-14',
    effectiveFrom: '2026-07-01',
    applicability: 'REVIEW_REQUIRED',
    generation: 'REFERENCE_ONLY',
  },
  {
    id: 'ap--osh-2020--ap-osh-2026--viii--aposh',
    jurisdiction: 'AP',
    actCode: 'OSH_2020',
    rulesCode: 'AP_OSH_2026',
    formNumber: 'VIII',
    title: 'Register of employees',
    ruleReference: 'Rule 32(1)(a)',
    kind: 'REGISTER',
    sourceId: 'aposh',
    sourceStatus: 'FINAL',
    sourcePage: 449,
    layoutId: 'ap-osh-viii',
    notes:
      'Rule 1(3): effective from final Gazette publication. Rule 32 requires original records for five calendar years after the last entry and manual entries in a language understood by the majority of employees. State-government applicability must be established independently; Central Rule 72(3) reuse is not applied to these state schedules.',
    verifiedOn: '2026-09-14',
    effectiveFrom: '2026-08-07',
    applicability: 'REVIEW_REQUIRED',
    generation: 'REFERENCE_ONLY',
  },
  {
    id: 'ap--osh-2020--ap-osh-2026--viii-a--aposh',
    jurisdiction: 'AP',
    actCode: 'OSH_2020',
    rulesCode: 'AP_OSH_2026',
    formNumber: 'VIII(A)',
    title: 'Attendance register-cum-muster roll',
    ruleReference: 'Rule 32(1)(a)',
    kind: 'REGISTER',
    sourceId: 'aposh',
    sourceStatus: 'FINAL',
    sourcePage: 450,
    layoutId: 'ap-osh-viii-a',
    notes:
      'Rule 1(3): effective from final Gazette publication. Rule 32 requires original records for five calendar years after the last entry and manual entries in a language understood by the majority of employees. State-government applicability must be established independently; Central Rule 72(3) reuse is not applied to these state schedules.',
    verifiedOn: '2026-09-14',
    effectiveFrom: '2026-08-07',
    applicability: 'REVIEW_REQUIRED',
    generation: 'REFERENCE_ONLY',
  },
  {
    id: 'ap--osh-2020--ap-osh-2026--ix--aposh',
    jurisdiction: 'AP',
    actCode: 'OSH_2020',
    rulesCode: 'AP_OSH_2026',
    formNumber: 'IX',
    title: 'Register for wages, overtime and deductions',
    ruleReference: 'Rule 32(1)(b)',
    kind: 'REGISTER',
    sourceId: 'aposh',
    sourceStatus: 'FINAL',
    sourcePage: 451,
    layoutId: 'ap-osh-ix',
    notes:
      'Rule 1(3): effective from final Gazette publication. Rule 32 requires original records for five calendar years after the last entry and manual entries in a language understood by the majority of employees. State-government applicability must be established independently; Central Rule 72(3) reuse is not applied to these state schedules.',
    verifiedOn: '2026-09-14',
    effectiveFrom: '2026-08-07',
    applicability: 'REVIEW_REQUIRED',
    generation: 'REFERENCE_ONLY',
  },
  {
    id: 'ap--osh-2020--ap-osh-2026--x--aposh',
    jurisdiction: 'AP',
    actCode: 'OSH_2020',
    rulesCode: 'AP_OSH_2026',
    formNumber: 'X',
    title: 'Register for leave with wages',
    ruleReference: 'Rule 32(1)(c)',
    kind: 'REGISTER',
    sourceId: 'aposh',
    sourceStatus: 'FINAL',
    sourcePage: 452,
    layoutId: 'ap-osh-x',
    notes:
      'Rule 1(3): effective from final Gazette publication. Rule 32 requires original records for five calendar years after the last entry and manual entries in a language understood by the majority of employees. State-government applicability must be established independently; Central Rule 72(3) reuse is not applied to these state schedules.',
    verifiedOn: '2026-09-14',
    effectiveFrom: '2026-08-07',
    applicability: 'REVIEW_REQUIRED',
    generation: 'REFERENCE_ONLY',
  },
  {
    id: 'ap--osh-2020--ap-osh-2026--xi--aposh',
    jurisdiction: 'AP',
    actCode: 'OSH_2020',
    rulesCode: 'AP_OSH_2026',
    formNumber: 'XI',
    title: 'Register of accidents and dangerous occurrences',
    ruleReference: 'Rule 32(1)(d)',
    kind: 'REGISTER',
    sourceId: 'aposh',
    sourceStatus: 'FINAL',
    sourcePage: 453,
    layoutId: 'ap-osh-xi',
    notes:
      'Rule 1(3): effective from final Gazette publication. Rule 32 requires original records for five calendar years after the last entry and manual entries in a language understood by the majority of employees. State-government applicability must be established independently; Central Rule 72(3) reuse is not applied to these state schedules.',
    verifiedOn: '2026-09-14',
    effectiveFrom: '2026-08-07',
    applicability: 'REVIEW_REQUIRED',
    generation: 'REFERENCE_ONLY',
  },
  {
    id: 'ar--wages-2019--arunachal-pradesh-wages-2022--i--arw',
    jurisdiction: 'AR',
    actCode: 'WAGES_2019',
    rulesCode: 'ARUNACHAL_PRADESH_WAGES_2022',
    formNumber: 'I',
    title: 'Wages, overtime, fines and deductions',
    ruleReference: 'Rules 15, 18, 19 and 50',
    kind: 'REGISTER',
    sourceId: 'arw',
    sourceStatus: 'FINAL',
    sourcePage: 10,
    layoutId: 'ar-wages-i',
    notes:
      'Code register preparation is limited to periods after S.O.5322(E), 21 November 2025. State-government applicability must be reviewed.',
    verifiedOn: '2026-09-14',
    effectiveFrom: '2025-11-21',
    applicability: 'REVIEW_REQUIRED',
    generation: 'REFERENCE_ONLY',
  },
  {
    id: 'ar--wages-2019--arunachal-pradesh-wages-2022--iv--arw',
    jurisdiction: 'AR',
    actCode: 'WAGES_2019',
    rulesCode: 'ARUNACHAL_PRADESH_WAGES_2022',
    formNumber: 'IV',
    title: 'Employee register',
    ruleReference: 'Rule 50(3)',
    kind: 'REGISTER',
    sourceId: 'arw',
    sourceStatus: 'FINAL',
    sourcePage: 13,
    layoutId: 'ar-wages-iv',
    notes:
      'Code register preparation is limited to periods after S.O.5322(E), 21 November 2025. State-government applicability must be reviewed.',
    verifiedOn: '2026-09-14',
    effectiveFrom: '2025-11-21',
    applicability: 'REVIEW_REQUIRED',
    generation: 'REFERENCE_ONLY',
  },
  {
    id: 'ar--wages-2019--arunachal-pradesh-wages-2022--v--arw',
    jurisdiction: 'AR',
    actCode: 'WAGES_2019',
    rulesCode: 'ARUNACHAL_PRADESH_WAGES_2022',
    formNumber: 'V',
    title: 'Wage slip',
    ruleReference: 'Rule 51',
    kind: 'WAGE_SLIP',
    sourceId: 'arw',
    sourceStatus: 'FINAL',
    sourcePage: 13,
    layoutId: 'ar-wages-v',
    notes:
      'Code register preparation is limited to periods after S.O.5322(E), 21 November 2025. State-government applicability must be reviewed.',
    verifiedOn: '2026-09-14',
    effectiveFrom: '2025-11-21',
    applicability: 'REVIEW_REQUIRED',
    generation: 'REFERENCE_ONLY',
  },
  {
    id: 'sk--wages-2019--sikkim-wages-2022--i--skw',
    jurisdiction: 'SK',
    actCode: 'WAGES_2019',
    rulesCode: 'SIKKIM_WAGES_2022',
    formNumber: 'I',
    title: 'Wages, overtime, fines and deductions for damage and loss',
    ruleReference: 'Rules 20 and 44',
    kind: 'REGISTER',
    sourceId: 'skw',
    sourceStatus: 'FINAL',
    sourcePage: 17,
    layoutId: 'sk-wages-i',
    notes:
      'Code register preparation is limited to periods after S.O.5322(E), 21 November 2025. State-government applicability must be reviewed.',
    verifiedOn: '2026-09-14',
    effectiveFrom: '2025-11-21',
    applicability: 'REVIEW_REQUIRED',
    generation: 'REFERENCE_ONLY',
  },
  {
    id: 'sk--wages-2019--sikkim-wages-2022--iv--skw',
    jurisdiction: 'SK',
    actCode: 'WAGES_2019',
    rulesCode: 'SIKKIM_WAGES_2022',
    formNumber: 'IV',
    title: 'Employee register',
    ruleReference: 'Rule 44(3)',
    kind: 'REGISTER',
    sourceId: 'skw',
    sourceStatus: 'FINAL',
    sourcePage: 21,
    layoutId: 'sk-wages-iv',
    notes:
      'Code register preparation is limited to periods after S.O.5322(E), 21 November 2025. State-government applicability must be reviewed.',
    verifiedOn: '2026-09-14',
    effectiveFrom: '2025-11-21',
    applicability: 'REVIEW_REQUIRED',
    generation: 'REFERENCE_ONLY',
  },
  {
    id: 'sk--wages-2019--sikkim-wages-2022--v--skw',
    jurisdiction: 'SK',
    actCode: 'WAGES_2019',
    rulesCode: 'SIKKIM_WAGES_2022',
    formNumber: 'V',
    title: 'Wage slip',
    ruleReference: 'Rule 45',
    kind: 'WAGE_SLIP',
    sourceId: 'skw',
    sourceStatus: 'FINAL',
    sourcePage: 22,
    layoutId: 'sk-wages-v',
    notes:
      'Code register preparation is limited to periods after S.O.5322(E), 21 November 2025. State-government applicability must be reviewed.',
    verifiedOn: '2026-09-14',
    effectiveFrom: '2025-11-21',
    applicability: 'REVIEW_REQUIRED',
    generation: 'REFERENCE_ONLY',
  },

  {
    id: 'br--wages-2019--bihar-wages-2026--i--brw',
    jurisdiction: 'BR',
    actCode: 'WAGES_2019',
    rulesCode: 'BIHAR_WAGES_2026',
    formNumber: 'I',
    title: 'Employee register',
    ruleReference: 'Rule 43',
    kind: 'REGISTER',
    sourceId: 'brw',
    sourceStatus: 'FINAL',
    sourcePage: 38,
    layoutId: 'br-wages-i',
    notes:
      'Rule 1(3): effective from Gazette publication. State-government applicability and the selected wage period must be reviewed.',
    verifiedOn: '2026-09-14',
    effectiveFrom: '2026-07-01',
    applicability: 'REVIEW_REQUIRED',
    generation: 'REFERENCE_ONLY',
  },
  {
    id: 'br--wages-2019--bihar-wages-2026--iv--brw',
    jurisdiction: 'BR',
    actCode: 'WAGES_2019',
    rulesCode: 'BIHAR_WAGES_2026',
    formNumber: 'IV',
    title:
      'Wages, overtime, advances, fines and deductions for damage and loss',
    ruleReference: 'Rule 43',
    kind: 'REGISTER',
    sourceId: 'brw',
    sourceStatus: 'FINAL',
    sourcePage: 42,
    layoutId: 'br-wages-iv',
    notes:
      'Rule 1(3): effective from Gazette publication. State-government applicability and the selected wage period must be reviewed.',
    verifiedOn: '2026-09-14',
    effectiveFrom: '2026-07-01',
    applicability: 'REVIEW_REQUIRED',
    generation: 'REFERENCE_ONLY',
  },
  {
    id: 'br--wages-2019--bihar-wages-2026--v--brw',
    jurisdiction: 'BR',
    actCode: 'WAGES_2019',
    rulesCode: 'BIHAR_WAGES_2026',
    formNumber: 'V',
    title: 'Wage slip',
    ruleReference: 'Rule 44',
    kind: 'WAGE_SLIP',
    sourceId: 'brw',
    sourceStatus: 'FINAL',
    sourcePage: 43,
    layoutId: 'br-wages-v',
    notes:
      'Rule 1(3): effective from Gazette publication. State-government applicability and the selected wage period must be reviewed.',
    verifiedOn: '2026-09-14',
    effectiveFrom: '2026-07-01',
    applicability: 'REVIEW_REQUIRED',
    generation: 'REFERENCE_ONLY',
  },
  {
    id: 'br--wages-2019--bihar-wages-2026--ix--brw',
    jurisdiction: 'BR',
    actCode: 'WAGES_2019',
    rulesCode: 'BIHAR_WAGES_2026',
    formNumber: 'IX',
    title: 'Attendance register cum muster roll',
    ruleReference: 'Rule 43',
    kind: 'REGISTER',
    sourceId: 'brw',
    sourceStatus: 'FINAL',
    sourcePage: 48,
    layoutId: 'br-wages-ix',
    notes:
      'Rule 1(3): effective from Gazette publication. State-government applicability and the selected wage period must be reviewed.',
    verifiedOn: '2026-09-14',
    effectiveFrom: '2026-07-01',
    applicability: 'REVIEW_REQUIRED',
    generation: 'REFERENCE_ONLY',
  },
  {
    id: 'la--wages-2019--ladakh-wages-2026--i--ldw',
    jurisdiction: 'LA',
    actCode: 'WAGES_2019',
    rulesCode: 'LADAKH_WAGES_2026',
    formNumber: 'I',
    title: 'Employee register',
    ruleReference: 'Rule 42',
    kind: 'REGISTER',
    sourceId: 'ldw',
    sourceStatus: 'FINAL',
    sourcePage: 25,
    layoutId: 'la-wages-i',
    notes:
      'Rule 1(3): effective from Gazette publication. State-government applicability and the selected wage period must be reviewed.',
    verifiedOn: '2026-09-14',
    effectiveFrom: '2026-08-03',
    applicability: 'REVIEW_REQUIRED',
    generation: 'REFERENCE_ONLY',
  },
  {
    id: 'la--wages-2019--ladakh-wages-2026--iv--ldw',
    jurisdiction: 'LA',
    actCode: 'WAGES_2019',
    rulesCode: 'LADAKH_WAGES_2026',
    formNumber: 'IV',
    title:
      'Wages, overtime, advances, fines and deductions for damage and loss',
    ruleReference: 'Rules 17 and 42',
    kind: 'REGISTER',
    sourceId: 'ldw',
    sourceStatus: 'FINAL',
    sourcePage: 30,
    layoutId: 'la-wages-iv',
    notes:
      'Rule 1(3): effective from Gazette publication. State-government applicability and the selected wage period must be reviewed.',
    verifiedOn: '2026-09-14',
    effectiveFrom: '2026-08-03',
    applicability: 'REVIEW_REQUIRED',
    generation: 'REFERENCE_ONLY',
  },
  {
    id: 'la--wages-2019--ladakh-wages-2026--v--ldw',
    jurisdiction: 'LA',
    actCode: 'WAGES_2019',
    rulesCode: 'LADAKH_WAGES_2026',
    formNumber: 'V',
    title: 'Wage slip',
    ruleReference: 'Rule 43',
    kind: 'WAGE_SLIP',
    sourceId: 'ldw',
    sourceStatus: 'FINAL',
    sourcePage: 31,
    layoutId: 'la-wages-v',
    notes:
      'Rule 1(3): effective from Gazette publication. State-government applicability and the selected wage period must be reviewed.',
    verifiedOn: '2026-09-14',
    effectiveFrom: '2026-08-03',
    applicability: 'REVIEW_REQUIRED',
    generation: 'REFERENCE_ONLY',
  },
  {
    id: 'la--wages-2019--ladakh-wages-2026--ix--ldw',
    jurisdiction: 'LA',
    actCode: 'WAGES_2019',
    rulesCode: 'LADAKH_WAGES_2026',
    formNumber: 'IX',
    title: 'Attendance register cum muster roll',
    ruleReference: 'Rule 42',
    kind: 'REGISTER',
    sourceId: 'ldw',
    sourceStatus: 'FINAL',
    sourcePage: 35,
    layoutId: 'la-wages-ix',
    notes:
      'Rule 1(3): effective from Gazette publication. State-government applicability and the selected wage period must be reviewed.',
    verifiedOn: '2026-09-14',
    effectiveFrom: '2026-08-03',
    applicability: 'REVIEW_REQUIRED',
    generation: 'REFERENCE_ONLY',
  },
  {
    id: 'up--wages-2019--uttar-pradesh-wages-2026--i--upw',
    jurisdiction: 'UP',
    actCode: 'WAGES_2019',
    rulesCode: 'UTTAR_PRADESH_WAGES_2026',
    formNumber: 'I',
    title: 'Wages, overtime, fines and deductions for damage and loss',
    ruleReference: 'Rules 17(8), 19(4), 20 and 40',
    kind: 'REGISTER',
    sourceId: 'upw',
    sourceStatus: 'FINAL',
    sourcePage: 63,
    layoutId: 'up-wages-i',
    notes:
      'Rule 1(3): effective from Gazette publication. State-government applicability and the selected wage period must be reviewed.',
    verifiedOn: '2026-09-14',
    effectiveFrom: '2026-08-12',
    applicability: 'REVIEW_REQUIRED',
    generation: 'REFERENCE_ONLY',
  },
  {
    id: 'up--wages-2019--uttar-pradesh-wages-2026--ii--upw',
    jurisdiction: 'UP',
    actCode: 'WAGES_2019',
    rulesCode: 'UTTAR_PRADESH_WAGES_2026',
    formNumber: 'II',
    title: 'Employee register',
    ruleReference: 'Rule 40(2)',
    kind: 'REGISTER',
    sourceId: 'upw',
    sourceStatus: 'FINAL',
    sourcePage: 63,
    layoutId: 'up-wages-ii',
    notes:
      'Rule 1(3): effective from Gazette publication. State-government applicability and the selected wage period must be reviewed.',
    verifiedOn: '2026-09-14',
    effectiveFrom: '2026-08-12',
    applicability: 'REVIEW_REQUIRED',
    generation: 'REFERENCE_ONLY',
  },
  {
    id: 'up--wages-2019--uttar-pradesh-wages-2026--ix--upw',
    jurisdiction: 'UP',
    actCode: 'WAGES_2019',
    rulesCode: 'UTTAR_PRADESH_WAGES_2026',
    formNumber: 'IX',
    title: 'Wage slip',
    ruleReference: 'Rule 42',
    kind: 'WAGE_SLIP',
    sourceId: 'upw',
    sourceStatus: 'FINAL',
    sourcePage: 68,
    layoutId: 'up-wages-ix',
    notes:
      'Rule 1(3): effective from Gazette publication. State-government applicability and the selected wage period must be reviewed.',
    verifiedOn: '2026-09-14',
    effectiveFrom: '2026-08-12',
    applicability: 'REVIEW_REQUIRED',
    generation: 'REFERENCE_ONLY',
  },

  {
    id: 'gj--wages-2019--gujarat-wages-2021--i--gjw',
    jurisdiction: 'GJ',
    actCode: 'WAGES_2019',
    rulesCode: 'GUJARAT_WAGES_2021',
    formNumber: 'I',
    title: 'Wages, overtime, fines and deductions for damage and loss',
    ruleReference: 'Rules 17 and 42(1)–(3)',
    kind: 'REGISTER',
    sourceId: 'gjw',
    sourceStatus: 'FINAL',
    sourcePage: 14,
    layoutId: 'gj-wages-i',
    notes:
      'Rule 1(3) ties commencement to the Code; S.O.5322(E) commenced the relevant provisions on 21 November 2025. State-government applicability must be checked.',
    verifiedOn: '2026-09-14',
    effectiveFrom: '2025-11-21',
    applicability: 'REVIEW_REQUIRED',
    generation: 'REFERENCE_ONLY',
  },
  {
    id: 'gj--wages-2019--gujarat-wages-2021--iv--gjw',
    jurisdiction: 'GJ',
    actCode: 'WAGES_2019',
    rulesCode: 'GUJARAT_WAGES_2021',
    formNumber: 'IV',
    title: 'Employee register',
    ruleReference: 'Rule 42(3)',
    kind: 'REGISTER',
    sourceId: 'gjw',
    sourceStatus: 'FINAL',
    sourcePage: 17,
    layoutId: 'gj-wages-iv',
    notes:
      'Rule 1(3) ties commencement to the Code; S.O.5322(E) commenced the relevant provisions on 21 November 2025. State-government applicability must be checked.',
    verifiedOn: '2026-09-14',
    effectiveFrom: '2025-11-21',
    applicability: 'REVIEW_REQUIRED',
    generation: 'REFERENCE_ONLY',
  },
  {
    id: 'gj--wages-2019--gujarat-wages-2021--v--gjw',
    jurisdiction: 'GJ',
    actCode: 'WAGES_2019',
    rulesCode: 'GUJARAT_WAGES_2021',
    formNumber: 'V',
    title: 'Wage slip',
    ruleReference: 'Rule 43',
    kind: 'WAGE_SLIP',
    sourceId: 'gjw',
    sourceStatus: 'FINAL',
    sourcePage: 17,
    layoutId: 'gj-wages-v',
    notes:
      'Rule 1(3) ties commencement to the Code; S.O.5322(E) commenced the relevant provisions on 21 November 2025. State-government applicability must be checked.',
    verifiedOn: '2026-09-14',
    effectiveFrom: '2025-11-21',
    applicability: 'REVIEW_REQUIRED',
    generation: 'REFERENCE_ONLY',
  },
  {
    id: 'rj--wages-2019--rajasthan-wages-2026--i--rjw',
    jurisdiction: 'RJ',
    actCode: 'WAGES_2019',
    rulesCode: 'RAJASTHAN_WAGES_2026',
    formNumber: 'I',
    title: 'Wages, overtime, fines and deductions for damage and loss',
    ruleReference: 'Rules 18 and 42(1)–(3)',
    kind: 'REGISTER',
    sourceId: 'rjw',
    sourceStatus: 'FINAL',
    sourcePage: 18,
    layoutId: 'rj-wages',
    notes:
      'Use Rajasthan state-government jurisdiction and the current applicability decision.',
    verifiedOn: '2026-09-14',
    effectiveFrom: '2026-08-12',
    applicability: 'REVIEW_REQUIRED',
    generation: 'REFERENCE_ONLY',
  },
  {
    id: 'rj--wages-2019--rajasthan-wages-2026--iv--rjw',
    jurisdiction: 'RJ',
    actCode: 'WAGES_2019',
    rulesCode: 'RAJASTHAN_WAGES_2026',
    formNumber: 'IV',
    title: 'Employee register',
    ruleReference: 'Rule 42(1)(i)',
    kind: 'REGISTER',
    sourceId: 'rjw',
    sourceStatus: 'FINAL',
    sourcePage: 24,
    layoutId: 'rj-employee',
    notes:
      'Use Rajasthan state-government jurisdiction and the current applicability decision.',
    verifiedOn: '2026-09-14',
    effectiveFrom: '2026-08-12',
    applicability: 'REVIEW_REQUIRED',
    generation: 'REFERENCE_ONLY',
  },
  {
    id: 'rj--wages-2019--rajasthan-wages-2026--v--rjw',
    jurisdiction: 'RJ',
    actCode: 'WAGES_2019',
    rulesCode: 'RAJASTHAN_WAGES_2026',
    formNumber: 'V',
    title: 'Muster roll and details of overtime work',
    ruleReference: 'Rule 42(1)(iii)',
    kind: 'REGISTER',
    sourceId: 'rjw',
    sourceStatus: 'FINAL',
    sourcePage: 25,
    layoutId: 'rj-muster',
    notes:
      'Use Rajasthan state-government jurisdiction and the current applicability decision.',
    verifiedOn: '2026-09-14',
    effectiveFrom: '2026-08-12',
    applicability: 'REVIEW_REQUIRED',
    generation: 'REFERENCE_ONLY',
  },
  {
    id: 'rj--wages-2019--rajasthan-wages-2026--vii--rjw',
    jurisdiction: 'RJ',
    actCode: 'WAGES_2019',
    rulesCode: 'RAJASTHAN_WAGES_2026',
    formNumber: 'VII',
    title: 'Wage slip',
    ruleReference: 'Rule 43',
    kind: 'WAGE_SLIP',
    sourceId: 'rjw',
    sourceStatus: 'FINAL',
    sourcePage: 26,
    layoutId: 'rj-slip',
    notes:
      'Use Rajasthan state-government jurisdiction and the current applicability decision.',
    verifiedOn: '2026-09-14',
    effectiveFrom: '2026-08-12',
    applicability: 'REVIEW_REQUIRED',
    generation: 'REFERENCE_ONLY',
  },
  {
    id: 'central--wages-2019--central-wages-2026--i--cw',
    jurisdiction: 'CENTRAL',
    actCode: 'WAGES_2019',
    rulesCode: 'CENTRAL_WAGES_2026',
    formNumber: 'I',
    title: 'Employee register',
    ruleReference: 'Rule 51(1)(i)',
    kind: 'REGISTER',
    sourceId: 'cw',
    sourceStatus: 'FINAL',
    sourcePage: 53,
    layoutId: 'wages-employee',
    notes: 'Check appropriate-government jurisdiction before use.',
    verifiedOn: '2026-09-14',
    effectiveFrom: '2026-05-08',
    applicability: 'REVIEW_REQUIRED',
    generation: 'REFERENCE_ONLY',
  },
  {
    id: 'central--wages-2019--central-wages-2026--iv--cw',
    jurisdiction: 'CENTRAL',
    actCode: 'WAGES_2019',
    rulesCode: 'CENTRAL_WAGES_2026',
    formNumber: 'IV',
    title:
      'Wages, overtime, advances, fines and deductions for damage and loss',
    ruleReference: 'Rule 51(1)(ii)',
    kind: 'REGISTER',
    sourceId: 'cw',
    sourceStatus: 'FINAL',
    sourcePage: 56,
    layoutId: 'wages-combined',
    notes: 'Check appropriate-government jurisdiction before use.',
    verifiedOn: '2026-09-14',
    effectiveFrom: '2026-05-08',
    applicability: 'REVIEW_REQUIRED',
    generation: 'REFERENCE_ONLY',
  },
  {
    id: 'central--wages-2019--central-wages-2026--ix--cw',
    jurisdiction: 'CENTRAL',
    actCode: 'WAGES_2019',
    rulesCode: 'CENTRAL_WAGES_2026',
    formNumber: 'IX',
    title: 'Attendance register-cum-muster roll',
    ruleReference: 'Rule 51(1)(iii)',
    kind: 'REGISTER',
    sourceId: 'cw',
    sourceStatus: 'FINAL',
    sourcePage: 60,
    layoutId: 'wages-attendance',
    notes: 'Check appropriate-government jurisdiction before use.',
    verifiedOn: '2026-09-14',
    effectiveFrom: '2026-05-08',
    applicability: 'REVIEW_REQUIRED',
    generation: 'REFERENCE_ONLY',
  },
  {
    id: 'central--wages-2019--central-wages-2026--v--cw',
    jurisdiction: 'CENTRAL',
    actCode: 'WAGES_2019',
    rulesCode: 'CENTRAL_WAGES_2026',
    formNumber: 'V',
    title: 'Wage slip',
    ruleReference: 'Rule 52',
    kind: 'WAGE_SLIP',
    sourceId: 'cw',
    sourceStatus: 'FINAL',
    sourcePage: 57,
    layoutId: 'wages-slip',
    notes: 'Check appropriate-government jurisdiction before use.',
    verifiedOn: '2026-09-14',
    effectiveFrom: '2026-05-08',
    applicability: 'REVIEW_REQUIRED',
    generation: 'REFERENCE_ONLY',
  },
  {
    id: 'ap--wages-2019--ap-wages-2026--i--apw',
    jurisdiction: 'AP',
    actCode: 'WAGES_2019',
    rulesCode: 'AP_WAGES_2026',
    formNumber: 'I',
    title: 'Employee register',
    ruleReference: 'Rule 42(1)(i)',
    kind: 'REGISTER',
    sourceId: 'apw',
    sourceStatus: 'FINAL',
    sourcePage: 15,
    layoutId: 'wages-employee',
    notes: 'Check appropriate-government jurisdiction before use.',
    verifiedOn: '2026-09-14',
    effectiveFrom: '2026-06-29',
    applicability: 'REVIEW_REQUIRED',
    generation: 'REFERENCE_ONLY',
  },
  {
    id: 'ap--wages-2019--ap-wages-2026--iv--apw',
    jurisdiction: 'AP',
    actCode: 'WAGES_2019',
    rulesCode: 'AP_WAGES_2026',
    formNumber: 'IV',
    title:
      'Wages, overtime, advances, fines and deductions for damage and loss',
    ruleReference: 'Rule 42(1)(ii)',
    kind: 'REGISTER',
    sourceId: 'apw',
    sourceStatus: 'FINAL',
    sourcePage: 21,
    layoutId: 'wages-combined',
    notes: 'Check appropriate-government jurisdiction before use.',
    verifiedOn: '2026-09-14',
    effectiveFrom: '2026-06-29',
    applicability: 'REVIEW_REQUIRED',
    generation: 'REFERENCE_ONLY',
  },
  {
    id: 'ap--wages-2019--ap-wages-2026--ix--apw',
    jurisdiction: 'AP',
    actCode: 'WAGES_2019',
    rulesCode: 'AP_WAGES_2026',
    formNumber: 'IX',
    title: 'Attendance register-cum-muster roll',
    ruleReference: 'Rule 42(1)(iii)',
    kind: 'REGISTER',
    sourceId: 'apw',
    sourceStatus: 'FINAL',
    sourcePage: 30,
    layoutId: 'wages-attendance',
    notes: 'Check appropriate-government jurisdiction before use.',
    verifiedOn: '2026-09-14',
    effectiveFrom: '2026-06-29',
    applicability: 'REVIEW_REQUIRED',
    generation: 'REFERENCE_ONLY',
  },
  {
    id: 'ap--wages-2019--ap-wages-2026--v--apw',
    jurisdiction: 'AP',
    actCode: 'WAGES_2019',
    rulesCode: 'AP_WAGES_2026',
    formNumber: 'V',
    title: 'Wage slip',
    ruleReference: 'Rule 43',
    kind: 'WAGE_SLIP',
    sourceId: 'apw',
    sourceStatus: 'FINAL',
    sourcePage: 23,
    layoutId: 'wages-slip',
    notes: 'Check appropriate-government jurisdiction before use.',
    verifiedOn: '2026-09-14',
    effectiveFrom: '2026-06-29',
    applicability: 'REVIEW_REQUIRED',
    generation: 'REFERENCE_ONLY',
  },
  {
    id: 'central--osh-2020--central-osh-2026--v--osh',
    jurisdiction: 'CENTRAL',
    actCode: 'OSH_2020',
    rulesCode: 'CENTRAL_OSH_2026',
    formNumber: 'V',
    title: 'Register of establishments',
    ruleReference: 'Rule 3(9)',
    kind: 'AUTHORITY_REGISTER',
    sourceId: 'osh',
    sourceStatus: 'FINAL',
    sourcePage: 251,
    layoutId: null,
    notes:
      'Maintained by the registering authority; not an employer payroll register.',
    verifiedOn: '2026-09-14',
    effectiveFrom: '2026-05-08',
    applicability: 'REVIEW_REQUIRED',
    generation: 'REFERENCE_ONLY',
  },
  {
    id: 'central--osh-2020--central-osh-2026--xi--osh',
    jurisdiction: 'CENTRAL',
    actCode: 'OSH_2020',
    rulesCode: 'CENTRAL_OSH_2026',
    formNumber: 'XI',
    title: 'Notice of accident or dangerous occurrence',
    ruleReference: 'Rule 7(1) and 7(2)',
    kind: 'NOTICE',
    sourceId: 'osh',
    sourceStatus: 'FINAL',
    sourcePage: 273,
    layoutId: null,
    notes: 'Prescribed source retained; data population is not enabled.',
    verifiedOn: '2026-09-14',
    effectiveFrom: '2026-05-08',
    applicability: 'REVIEW_REQUIRED',
    generation: 'REFERENCE_ONLY',
  },
  {
    id: 'central--osh-2020--central-osh-2026--xii--osh',
    jurisdiction: 'CENTRAL',
    actCode: 'OSH_2020',
    rulesCode: 'CENTRAL_OSH_2026',
    formNumber: 'XII',
    title: 'Notice of periods of work',
    ruleReference: 'Rule 71',
    kind: 'NOTICE',
    sourceId: 'osh',
    sourceStatus: 'FINAL',
    sourcePage: 280,
    layoutId: null,
    notes: 'Prescribed source retained; data population is not enabled.',
    verifiedOn: '2026-09-14',
    effectiveFrom: '2026-05-08',
    applicability: 'REVIEW_REQUIRED',
    generation: 'REFERENCE_ONLY',
  },
  {
    id: 'central--osh-2020--central-osh-2026--xiii--osh',
    jurisdiction: 'CENTRAL',
    actCode: 'OSH_2020',
    rulesCode: 'CENTRAL_OSH_2026',
    formNumber: 'XIII',
    title: 'Employee register',
    ruleReference: 'Rule 72(1)(i)',
    kind: 'REGISTER',
    sourceId: 'osh',
    sourceStatus: 'FINAL',
    sourcePage: 281,
    layoutId: 'osh-employee',
    notes: 'Prescribed source retained; data population is not enabled.',
    verifiedOn: '2026-09-14',
    effectiveFrom: '2026-05-08',
    applicability: 'REVIEW_REQUIRED',
    generation: 'REFERENCE_ONLY',
  },
  {
    id: 'central--osh-2020--central-osh-2026--xiv--osh',
    jurisdiction: 'CENTRAL',
    actCode: 'OSH_2020',
    rulesCode: 'CENTRAL_OSH_2026',
    formNumber: 'XIV',
    title: 'Attendance register-cum-muster roll',
    ruleReference: 'Rule 72(1)(ii)',
    kind: 'REGISTER',
    sourceId: 'osh',
    sourceStatus: 'FINAL',
    sourcePage: 283,
    layoutId: 'osh-attendance',
    notes: 'Prescribed source retained; data population is not enabled.',
    verifiedOn: '2026-09-14',
    effectiveFrom: '2026-05-08',
    applicability: 'REVIEW_REQUIRED',
    generation: 'REFERENCE_ONLY',
  },
  {
    id: 'central--osh-2020--central-osh-2026--xv--osh',
    jurisdiction: 'CENTRAL',
    actCode: 'OSH_2020',
    rulesCode: 'CENTRAL_OSH_2026',
    formNumber: 'XV',
    title: 'Wages, overtime and deductions',
    ruleReference: 'Rule 72(1)(iii)',
    kind: 'REGISTER',
    sourceId: 'osh',
    sourceStatus: 'FINAL',
    sourcePage: 284,
    layoutId: 'osh-wages',
    notes: 'Prescribed source retained; data population is not enabled.',
    verifiedOn: '2026-09-14',
    effectiveFrom: '2026-05-08',
    applicability: 'REVIEW_REQUIRED',
    generation: 'REFERENCE_ONLY',
  },
  {
    id: 'central--osh-2020--central-osh-2026--xvi--osh',
    jurisdiction: 'CENTRAL',
    actCode: 'OSH_2020',
    rulesCode: 'CENTRAL_OSH_2026',
    formNumber: 'XVI',
    title: 'Wage slip',
    ruleReference: 'Rule 72(2)',
    kind: 'WAGE_SLIP',
    sourceId: 'osh',
    sourceStatus: 'FINAL',
    sourcePage: 286,
    layoutId: 'osh-slip',
    notes: 'Prescribed source retained; data population is not enabled.',
    verifiedOn: '2026-09-14',
    effectiveFrom: '2026-05-08',
    applicability: 'REVIEW_REQUIRED',
    generation: 'REFERENCE_ONLY',
  },
  {
    id: 'central--osh-2020--central-osh-2026--xvii--osh',
    jurisdiction: 'CENTRAL',
    actCode: 'OSH_2020',
    rulesCode: 'CENTRAL_OSH_2026',
    formNumber: 'XVII',
    title: 'Annual return',
    ruleReference: 'Rule 72(5)',
    kind: 'RETURN',
    sourceId: 'osh',
    sourceStatus: 'FINAL',
    sourcePage: 287,
    layoutId: null,
    notes: 'Prescribed source retained; data population is not enabled.',
    verifiedOn: '2026-09-14',
    effectiveFrom: '2026-05-08',
    applicability: 'REVIEW_REQUIRED',
    generation: 'REFERENCE_ONLY',
  },
  {
    id: 'central--osh-2020--central-osh-2026--xviii--osh',
    jurisdiction: 'CENTRAL',
    actCode: 'OSH_2020',
    rulesCode: 'CENTRAL_OSH_2026',
    formNumber: 'XVIII',
    title: 'Contractor half-yearly return',
    ruleReference: 'Rule 72(5) and 98(7)',
    kind: 'RETURN',
    sourceId: 'osh',
    sourceStatus: 'FINAL',
    sourcePage: 303,
    layoutId: null,
    notes: 'Prescribed source retained; data population is not enabled.',
    verifiedOn: '2026-09-14',
    effectiveFrom: '2026-05-08',
    applicability: 'REVIEW_REQUIRED',
    generation: 'REFERENCE_ONLY',
  },
  {
    id: 'central--osh-2020--central-osh-2026--xix--osh',
    jurisdiction: 'CENTRAL',
    actCode: 'OSH_2020',
    rulesCode: 'CENTRAL_OSH_2026',
    formNumber: 'XIX',
    title: 'Accidents and dangerous occurrences',
    ruleReference: 'Rule 75',
    kind: 'REGISTER',
    sourceId: 'osh',
    sourceStatus: 'FINAL',
    sourcePage: 304,
    layoutId: 'osh-accident',
    notes: 'Prescribed source retained; data population is not enabled.',
    verifiedOn: '2026-09-14',
    effectiveFrom: '2026-05-08',
    applicability: 'REVIEW_REQUIRED',
    generation: 'REFERENCE_ONLY',
  },
  {
    id: 'central--osh-2020--central-osh-2026--xx--osh',
    jurisdiction: 'CENTRAL',
    actCode: 'OSH_2020',
    rulesCode: 'CENTRAL_OSH_2026',
    formNumber: 'XX',
    title: 'Leave with wages',
    ruleReference: 'Rule 76',
    kind: 'REGISTER',
    sourceId: 'osh',
    sourceStatus: 'FINAL',
    sourcePage: 305,
    layoutId: 'osh-leave',
    notes: 'Prescribed source retained; data population is not enabled.',
    verifiedOn: '2026-09-14',
    effectiveFrom: '2026-05-08',
    applicability: 'REVIEW_REQUIRED',
    generation: 'REFERENCE_ONLY',
  },
  {
    id: 'central--osh-2020--central-osh-2026--xxiii--osh',
    jurisdiction: 'CENTRAL',
    actCode: 'OSH_2020',
    rulesCode: 'CENTRAL_OSH_2026',
    formNumber: 'XXIII',
    title: 'Experience certificate of contract labour',
    ruleReference: 'Rule 100',
    kind: 'CERTIFICATE',
    sourceId: 'osh',
    sourceStatus: 'FINAL',
    sourcePage: 310,
    layoutId: null,
    notes: 'Prescribed source retained; data population is not enabled.',
    verifiedOn: '2026-09-14',
    effectiveFrom: '2026-05-08',
    applicability: 'REVIEW_REQUIRED',
    generation: 'REFERENCE_ONLY',
  },
  {
    id: 'central--social-security-2020--central-ss-2026--xxii--ss',
    jurisdiction: 'CENTRAL',
    actCode: 'SOCIAL_SECURITY_2020',
    rulesCode: 'CENTRAL_SS_2026',
    formNumber: 'XXII',
    title: 'Women employees register',
    ruleReference: 'Rule 53(1)(a)',
    kind: 'REGISTER',
    sourceId: 'ss',
    sourceStatus: 'FINAL',
    sourcePage: 232,
    layoutId: null,
    notes:
      'Maternity-related event records require authorised HR input. Rule 53 also recognises common Wages/OSH registers; avoid duplicate payroll records.',
    verifiedOn: '2026-09-14',
    effectiveFrom: '2026-05-08',
    applicability: 'REVIEW_REQUIRED',
    generation: 'REFERENCE_ONLY',
  },
  {
    id: 'central--ir-2020--central-ir-2026--iii--ir',
    jurisdiction: 'CENTRAL',
    actCode: 'IR_2020',
    rulesCode: 'CENTRAL_IR_2026',
    formNumber: 'III',
    title: 'Register of standing orders',
    ruleReference: 'Rule 17',
    kind: 'AUTHORITY_REGISTER',
    sourceId: 'ir',
    sourceStatus: 'FINAL',
    sourcePage: null,
    layoutId: null,
    notes:
      'Maintained by the certifying officer, not generated as an employer payroll register.',
    verifiedOn: '2026-09-14',
    effectiveFrom: '2026-05-08',
    applicability: 'REVIEW_REQUIRED',
    generation: 'REFERENCE_ONLY',
  },
  {
    id: 'ts--multi-act--ts-integrated-2019--ii---iii--tsi',
    jurisdiction: 'TS',
    actCode: 'MULTI_ACT',
    rulesCode: 'TS_INTEGRATED_2019',
    formNumber: 'II + III',
    title: 'Integrated register (both forms together)',
    ruleReference: 'G.O.Ms.No.6, paragraphs 3–4',
    kind: 'REGISTER',
    sourceId: 'tsi',
    sourceStatus: 'EXISTING_RULES',
    sourcePage: 12,
    layoutId: 'ts-integrated',
    notes:
      'Both parts are required. Review current Code transition before operational use.',
    verifiedOn: '2026-09-14',
    effectiveFrom: null,
    applicability: 'REVIEW_REQUIRED',
    generation: 'REFERENCE_ONLY',
  },
  {
    id: 'ts--multi-act--ts-integrated-2019--i--tsi',
    jurisdiction: 'TS',
    actCode: 'MULTI_ACT',
    rulesCode: 'TS_INTEGRATED_2019',
    formNumber: 'I',
    title: 'Common annual return',
    ruleReference: 'G.O.Ms.No.6, paragraph 4',
    kind: 'RETURN',
    sourceId: 'tsi',
    sourceStatus: 'EXISTING_RULES',
    sourcePage: 4,
    layoutId: null,
    notes: 'Annual return, not a monthly register.',
    verifiedOn: '2026-09-14',
    effectiveFrom: null,
    applicability: 'REVIEW_REQUIRED',
    generation: 'REFERENCE_ONLY',
  },
  {
    id: 'mh--shops-2017--mh-shops-2018--q--mh',
    jurisdiction: 'MH',
    actCode: 'SHOPS_2017',
    rulesCode: 'MH_SHOPS_2018',
    formNumber: 'Q',
    title: 'Muster-roll cum wage register',
    ruleReference: 'Rule 26(1)',
    kind: 'REGISTER',
    sourceId: 'mh',
    sourceStatus: 'EXISTING_RULES',
    sourcePage: 90,
    layoutId: 'mh-shops-q',
    notes:
      'State Shops Act format; do not replace with a CLRA form carrying the same title.',
    verifiedOn: '2026-09-14',
    effectiveFrom: null,
    applicability: 'REVIEW_REQUIRED',
    generation: 'REFERENCE_ONLY',
  },
  {
    id: 'tn--factories-1948--tn-factories-1950-amend-2021--12--tn',
    jurisdiction: 'TN',
    actCode: 'FACTORIES_1948',
    rulesCode: 'TN_FACTORIES_1950_AMEND_2021',
    formNumber: '12',
    title: 'Adult workers and young persons',
    ruleReference: 'Rules 80 and 86',
    kind: 'REGISTER',
    sourceId: 'tn',
    sourceStatus: 'EXISTING_RULES',
    sourcePage: 3,
    layoutId: null,
    notes: '2021 amendment source; current Code transition requires review.',
    verifiedOn: '2026-09-14',
    effectiveFrom: null,
    applicability: 'REVIEW_REQUIRED',
    generation: 'REFERENCE_ONLY',
  },
  {
    id: 'tn--factories-1948--tn-factories-1950-amend-2021--15--tn',
    jurisdiction: 'TN',
    actCode: 'FACTORIES_1948',
    rulesCode: 'TN_FACTORIES_1950_AMEND_2021',
    formNumber: '15',
    title: 'Leave with wages',
    ruleReference: 'Rules 87 and 88',
    kind: 'REGISTER',
    sourceId: 'tn',
    sourceStatus: 'EXISTING_RULES',
    sourcePage: 4,
    layoutId: null,
    notes: '2021 amendment source; current Code transition requires review.',
    verifiedOn: '2026-09-14',
    effectiveFrom: null,
    applicability: 'REVIEW_REQUIRED',
    generation: 'REFERENCE_ONLY',
  },
  {
    id: 'tn--factories-1948--tn-factories-1950-amend-2021--25--tn',
    jurisdiction: 'TN',
    actCode: 'FACTORIES_1948',
    rulesCode: 'TN_FACTORIES_1950_AMEND_2021',
    formNumber: '25',
    title: 'Muster roll',
    ruleReference: 'Rule 103',
    kind: 'REGISTER',
    sourceId: 'tn',
    sourceStatus: 'EXISTING_RULES',
    sourcePage: 5,
    layoutId: null,
    notes: '2021 amendment source; current Code transition requires review.',
    verifiedOn: '2026-09-14',
    effectiveFrom: null,
    applicability: 'REVIEW_REQUIRED',
    generation: 'REFERENCE_ONLY',
  },
  {
    id: 'central--clra-1970--central-clra-1971--xii--clra',
    jurisdiction: 'CENTRAL',
    actCode: 'CLRA_1970',
    rulesCode: 'CENTRAL_CLRA_1971',
    formNumber: 'XII',
    title: 'Register of contractors',
    ruleReference: 'Rule 74',
    kind: 'REGISTER',
    sourceId: 'clra',
    sourceStatus: 'LEGACY',
    sourcePage: null,
    layoutId: 'clra-xii',
    notes:
      'Historical format; central 2026 OSH rules supersede these rules subject to savings.',
    verifiedOn: '2026-09-14',
    effectiveFrom: null,
    applicability: 'REVIEW_REQUIRED',
    generation: 'REFERENCE_ONLY',
  },
  {
    id: 'central--clra-1970--central-clra-1971--xiii--clra',
    jurisdiction: 'CENTRAL',
    actCode: 'CLRA_1970',
    rulesCode: 'CENTRAL_CLRA_1971',
    formNumber: 'XIII',
    title: 'Workmen employed by contractor',
    ruleReference: 'Rule 75',
    kind: 'REGISTER',
    sourceId: 'clra',
    sourceStatus: 'LEGACY',
    sourcePage: null,
    layoutId: 'clra-xiii',
    notes:
      'Historical format; central 2026 OSH rules supersede these rules subject to savings.',
    verifiedOn: '2026-09-14',
    effectiveFrom: null,
    applicability: 'REVIEW_REQUIRED',
    generation: 'REFERENCE_ONLY',
  },
  {
    id: 'central--clra-1970--central-clra-1971--xiv--clra',
    jurisdiction: 'CENTRAL',
    actCode: 'CLRA_1970',
    rulesCode: 'CENTRAL_CLRA_1971',
    formNumber: 'XIV',
    title: 'Employment card',
    ruleReference: 'Rule 76',
    kind: 'CARD',
    sourceId: 'clra',
    sourceStatus: 'LEGACY',
    sourcePage: null,
    layoutId: 'clra-xiv',
    notes:
      'Historical format; central 2026 OSH rules supersede these rules subject to savings.',
    verifiedOn: '2026-09-14',
    effectiveFrom: null,
    applicability: 'REVIEW_REQUIRED',
    generation: 'REFERENCE_ONLY',
  },
  {
    id: 'central--clra-1970--central-clra-1971--xv--clra',
    jurisdiction: 'CENTRAL',
    actCode: 'CLRA_1970',
    rulesCode: 'CENTRAL_CLRA_1971',
    formNumber: 'XV',
    title: 'Service certificate',
    ruleReference: 'Rule 77',
    kind: 'CERTIFICATE',
    sourceId: 'clra',
    sourceStatus: 'LEGACY',
    sourcePage: null,
    layoutId: 'clra-xv',
    notes:
      'Historical format; central 2026 OSH rules supersede these rules subject to savings.',
    verifiedOn: '2026-09-14',
    effectiveFrom: null,
    applicability: 'REVIEW_REQUIRED',
    generation: 'REFERENCE_ONLY',
  },
  {
    id: 'central--clra-1970--central-clra-1971--xvi--clra',
    jurisdiction: 'CENTRAL',
    actCode: 'CLRA_1970',
    rulesCode: 'CENTRAL_CLRA_1971',
    formNumber: 'XVI',
    title: 'Muster roll',
    ruleReference: 'Rule 78(1)(a)(i)',
    kind: 'REGISTER',
    sourceId: 'clra',
    sourceStatus: 'LEGACY',
    sourcePage: null,
    layoutId: 'clra-xvi',
    notes:
      'Historical format; central 2026 OSH rules supersede these rules subject to savings.',
    verifiedOn: '2026-09-14',
    effectiveFrom: null,
    applicability: 'REVIEW_REQUIRED',
    generation: 'REFERENCE_ONLY',
  },
  {
    id: 'central--clra-1970--central-clra-1971--xvii--clra',
    jurisdiction: 'CENTRAL',
    actCode: 'CLRA_1970',
    rulesCode: 'CENTRAL_CLRA_1971',
    formNumber: 'XVII',
    title: 'Register of wages',
    ruleReference: 'Rule 78(1)(a)(i)',
    kind: 'REGISTER',
    sourceId: 'clra',
    sourceStatus: 'LEGACY',
    sourcePage: null,
    layoutId: 'clra-xvii',
    notes:
      'Historical format; central 2026 OSH rules supersede these rules subject to savings.',
    verifiedOn: '2026-09-14',
    effectiveFrom: null,
    applicability: 'REVIEW_REQUIRED',
    generation: 'REFERENCE_ONLY',
  },
  {
    id: 'central--clra-1970--central-clra-1971--xviii--clra',
    jurisdiction: 'CENTRAL',
    actCode: 'CLRA_1970',
    rulesCode: 'CENTRAL_CLRA_1971',
    formNumber: 'XVIII',
    title: 'Wage-cum-muster roll',
    ruleReference: 'Rule 78(1)(a)(i)',
    kind: 'REGISTER',
    sourceId: 'clra',
    sourceStatus: 'LEGACY',
    sourcePage: null,
    layoutId: 'clra-xviii',
    notes:
      'Historical format; central 2026 OSH rules supersede these rules subject to savings.',
    verifiedOn: '2026-09-14',
    effectiveFrom: null,
    applicability: 'REVIEW_REQUIRED',
    generation: 'REFERENCE_ONLY',
  },
  {
    id: 'central--clra-1970--central-clra-1971--xix--clra',
    jurisdiction: 'CENTRAL',
    actCode: 'CLRA_1970',
    rulesCode: 'CENTRAL_CLRA_1971',
    formNumber: 'XIX',
    title: 'Wage slip',
    ruleReference: 'Rule 78(1)(b)',
    kind: 'WAGE_SLIP',
    sourceId: 'clra',
    sourceStatus: 'LEGACY',
    sourcePage: null,
    layoutId: 'clra-xix',
    notes:
      'Historical format; central 2026 OSH rules supersede these rules subject to savings.',
    verifiedOn: '2026-09-14',
    effectiveFrom: null,
    applicability: 'REVIEW_REQUIRED',
    generation: 'REFERENCE_ONLY',
  },
  {
    id: 'central--clra-1970--central-clra-1971--xx--clra',
    jurisdiction: 'CENTRAL',
    actCode: 'CLRA_1970',
    rulesCode: 'CENTRAL_CLRA_1971',
    formNumber: 'XX',
    title: 'Deductions for damage or loss',
    ruleReference: 'Rule 78(1)(a)(ii)',
    kind: 'REGISTER',
    sourceId: 'clra',
    sourceStatus: 'LEGACY',
    sourcePage: null,
    layoutId: 'clra-xx',
    notes:
      'Historical format; central 2026 OSH rules supersede these rules subject to savings.',
    verifiedOn: '2026-09-14',
    effectiveFrom: null,
    applicability: 'REVIEW_REQUIRED',
    generation: 'REFERENCE_ONLY',
  },
  {
    id: 'central--clra-1970--central-clra-1971--xxi--clra',
    jurisdiction: 'CENTRAL',
    actCode: 'CLRA_1970',
    rulesCode: 'CENTRAL_CLRA_1971',
    formNumber: 'XXI',
    title: 'Fines',
    ruleReference: 'Rule 78(1)(a)(ii)',
    kind: 'REGISTER',
    sourceId: 'clra',
    sourceStatus: 'LEGACY',
    sourcePage: null,
    layoutId: 'clra-xxi',
    notes:
      'Historical format; central 2026 OSH rules supersede these rules subject to savings.',
    verifiedOn: '2026-09-14',
    effectiveFrom: null,
    applicability: 'REVIEW_REQUIRED',
    generation: 'REFERENCE_ONLY',
  },
  {
    id: 'central--clra-1970--central-clra-1971--xxii--clra',
    jurisdiction: 'CENTRAL',
    actCode: 'CLRA_1970',
    rulesCode: 'CENTRAL_CLRA_1971',
    formNumber: 'XXII',
    title: 'Advances',
    ruleReference: 'Rule 78(1)(a)(ii)',
    kind: 'REGISTER',
    sourceId: 'clra',
    sourceStatus: 'LEGACY',
    sourcePage: null,
    layoutId: 'clra-xxii',
    notes:
      'Historical format; central 2026 OSH rules supersede these rules subject to savings.',
    verifiedOn: '2026-09-14',
    effectiveFrom: null,
    applicability: 'REVIEW_REQUIRED',
    generation: 'REFERENCE_ONLY',
  },
  {
    id: 'central--clra-1970--central-clra-1971--xxiii--clra',
    jurisdiction: 'CENTRAL',
    actCode: 'CLRA_1970',
    rulesCode: 'CENTRAL_CLRA_1971',
    formNumber: 'XXIII',
    title: 'Overtime',
    ruleReference: 'Rule 78(1)(a)(iii)',
    kind: 'REGISTER',
    sourceId: 'clra',
    sourceStatus: 'LEGACY',
    sourcePage: null,
    layoutId: 'clra-xxiii',
    notes:
      'Historical format; central 2026 OSH rules supersede these rules subject to savings.',
    verifiedOn: '2026-09-14',
    effectiveFrom: null,
    applicability: 'REVIEW_REQUIRED',
    generation: 'REFERENCE_ONLY',
  },
] as const;
