/** Source identity is separate from layout identity. Never match on title or form number alone. */
export const REGISTER_SOURCES = {
  gjw: {
    url: 'https://cdn.labourcodesadvisor.com/Rules/gujarat/final-wages-rules.pdf',
    title: 'Code on Wages (Gujarat) Rules, 2021',
    notification: 'KHR/2021/128/LVD/10/2020/555709/M(2)',
    publicationDate: '2021-10-05',
    publisher:
      'Government of Gujarat (notification copy hosted by Labour Code Advisor)',
  },
  rjw: {
    url: 'https://cdn.labourcodesadvisor.com/Rules/rajasthan/final-wages-rules.pdf',
    title: 'Code on Wages (Rajasthan) Rules, 2026',
    notification: 'S.O.40, Rajasthan Gazette',
    publicationDate: '2026-08-12',
    publisher:
      'Government of Rajasthan (Gazette copy hosted by Labour Code Advisor)',
  },
  cw: {
    url: 'https://www.labour.gov.in/static/uploads/2026/05/6eb0c35ba63b776487a025e5123b6b12.pdf',
    title: 'Code on Wages (Central) Rules, 2026',
    notification: 'G.S.R.343(E)',
    publicationDate: '2026-05-08',
    publisher: 'Ministry of Labour and Employment',
  },
  osh: {
    url: 'https://www.labour.gov.in/static/uploads/2026/05/ee246f790cad0b8e99c3828f34fa09a6.pdf',
    title:
      'Occupational Safety, Health and Working Conditions (Central) Rules, 2026',
    notification: 'G.S.R.345(E)',
    publicationDate: '2026-05-08',
    publisher: 'Ministry of Labour and Employment',
  },
  ss: {
    url: 'https://www.labour.gov.in/static/uploads/2026/05/49aa9b62c2125499c37399b90e969d67.pdf',
    title: 'Code on Social Security (Central) Rules, 2026',
    notification: 'G.S.R.344(E)',
    publicationDate: '2026-05-08',
    publisher: 'Ministry of Labour and Employment',
  },
  ir: {
    url: 'https://www.labour.gov.in/static/uploads/2026/05/f05a2c220dcdec0ea9c55e84d9ff791f.pdf',
    title: 'Industrial Relations (Central) Rules, 2026',
    notification: 'G.S.R.342(E)',
    publicationDate: '2026-05-08',
    publisher: 'Ministry of Labour and Employment',
  },
  apw: {
    url: 'https://www.ricago.com/assets/front/base/file/file_management/6536.pdf',
    title: 'Code on Wages (Andhra Pradesh) Rules, 2026',
    notification: 'G.O.Rt.No.124; Gazette No.328',
    publicationDate: '2026-06-29',
    publisher: 'Government of Andhra Pradesh (Gazette copy hosted by Ricago)',
  },
  tsi: {
    url: 'https://ipass.telangana.gov.in/viewpdf.aspx?filepathnew=D%3A%2FTS-iPASSFinal%2Fdocs%2F2019LETF_MS6+%282%29.PDF',
    title: 'Telangana integrated registers order, 2019',
    notification: 'G.O.Ms.No.6',
    publicationDate: '2019-03-02',
    publisher: 'Government of Telangana',
  },
  mh: {
    url: 'https://mahakamgar.maharashtra.gov.in/Site/Upload/PDF/Regulation_of_Employment_Conditions_of_Service_Rules_2018.pdf',
    title:
      'Maharashtra Shops and Establishments (Regulation of Employment and Conditions of Service) Rules, 2018',
    notification: 'Gazette, 23 March 2018',
    publicationDate: '2018-03-23',
    publisher: 'Government of Maharashtra',
  },
  tn: {
    url: 'https://dish.tn.gov.in/assets/pdf/Amendment%20of%20Rules%20for%20Maintenance%20of%20registers.pdf',
    title: 'Tamil Nadu Factories Rules amendment, 2021',
    notification: 'Tamil Nadu Government Gazette, 24 March 2021',
    publicationDate: '2021-03-24',
    publisher: 'Government of Tamil Nadu',
  },
  clra: {
    url: 'https://clc.gov.in/clc/acts-rules/contract-labour-regulation-abolition-act-1970',
    title: 'Contract Labour (Regulation and Abolition) Central Rules, 1971',
    notification: 'Legacy rules, subject to repeal and savings',
    publicationDate: null,
    publisher: 'Chief Labour Commissioner (Central)',
  },
} as const;

export const REGISTER_FORMS = [
  {
    id: 'gj--wages-2019--gujarat-wages-2021--i--gjw',
    jurisdiction: 'GJ',
    actCode: 'WAGES_2019',
    rulesCode: 'GUJARAT_WAGES_2021',
    formNumber: 'I',
    title: 'Wages, overtime, fines and deductions for damage and loss',
    ruleReference: 'Rules 17 and 42(1)–(3)',
    kind: 'REGISTER',
    sourceId: 'gjw',
    sourceStatus: 'FINAL',
    sourcePage: 14,
    layoutId: 'gj-wages-i',
    notes:
      'Rule 1(3) ties commencement to the Code; S.O.5322(E) commenced the relevant provisions on 21 November 2025. State-government applicability must be checked.',
    verifiedOn: '2026-09-14',
    effectiveFrom: '2025-11-21',
    applicability: 'REVIEW_REQUIRED',
    generation: 'REFERENCE_ONLY',
  },
  {
    id: 'gj--wages-2019--gujarat-wages-2021--iv--gjw',
    jurisdiction: 'GJ',
    actCode: 'WAGES_2019',
    rulesCode: 'GUJARAT_WAGES_2021',
    formNumber: 'IV',
    title: 'Employee register',
    ruleReference: 'Rule 42(3)',
    kind: 'REGISTER',
    sourceId: 'gjw',
    sourceStatus: 'FINAL',
    sourcePage: 17,
    layoutId: 'gj-wages-iv',
    notes:
      'Rule 1(3) ties commencement to the Code; S.O.5322(E) commenced the relevant provisions on 21 November 2025. State-government applicability must be checked.',
    verifiedOn: '2026-09-14',
    effectiveFrom: '2025-11-21',
    applicability: 'REVIEW_REQUIRED',
    generation: 'REFERENCE_ONLY',
  },
  {
    id: 'gj--wages-2019--gujarat-wages-2021--v--gjw',
    jurisdiction: 'GJ',
    actCode: 'WAGES_2019',
    rulesCode: 'GUJARAT_WAGES_2021',
    formNumber: 'V',
    title: 'Wage slip',
    ruleReference: 'Rule 43',
    kind: 'WAGE_SLIP',
    sourceId: 'gjw',
    sourceStatus: 'FINAL',
    sourcePage: 17,
    layoutId: 'gj-wages-v',
    notes:
      'Rule 1(3) ties commencement to the Code; S.O.5322(E) commenced the relevant provisions on 21 November 2025. State-government applicability must be checked.',
    verifiedOn: '2026-09-14',
    effectiveFrom: '2025-11-21',
    applicability: 'REVIEW_REQUIRED',
    generation: 'REFERENCE_ONLY',
  },
  {
    id: 'rj--wages-2019--rajasthan-wages-2026--i--rjw',
    jurisdiction: 'RJ',
    actCode: 'WAGES_2019',
    rulesCode: 'RAJASTHAN_WAGES_2026',
    formNumber: 'I',
    title: 'Wages, overtime, fines and deductions for damage and loss',
    ruleReference: 'Rules 18 and 42(1)–(3)',
    kind: 'REGISTER',
    sourceId: 'rjw',
    sourceStatus: 'FINAL',
    sourcePage: 18,
    layoutId: 'rj-wages',
    notes:
      'Use Rajasthan state-government jurisdiction and the current applicability decision.',
    verifiedOn: '2026-09-14',
    effectiveFrom: '2026-08-12',
    applicability: 'REVIEW_REQUIRED',
    generation: 'REFERENCE_ONLY',
  },
  {
    id: 'rj--wages-2019--rajasthan-wages-2026--iv--rjw',
    jurisdiction: 'RJ',
    actCode: 'WAGES_2019',
    rulesCode: 'RAJASTHAN_WAGES_2026',
    formNumber: 'IV',
    title: 'Employee register',
    ruleReference: 'Rule 42(1)(i)',
    kind: 'REGISTER',
    sourceId: 'rjw',
    sourceStatus: 'FINAL',
    sourcePage: 24,
    layoutId: 'rj-employee',
    notes:
      'Use Rajasthan state-government jurisdiction and the current applicability decision.',
    verifiedOn: '2026-09-14',
    effectiveFrom: '2026-08-12',
    applicability: 'REVIEW_REQUIRED',
    generation: 'REFERENCE_ONLY',
  },
  {
    id: 'rj--wages-2019--rajasthan-wages-2026--v--rjw',
    jurisdiction: 'RJ',
    actCode: 'WAGES_2019',
    rulesCode: 'RAJASTHAN_WAGES_2026',
    formNumber: 'V',
    title: 'Muster roll and details of overtime work',
    ruleReference: 'Rule 42(1)(iii)',
    kind: 'REGISTER',
    sourceId: 'rjw',
    sourceStatus: 'FINAL',
    sourcePage: 25,
    layoutId: 'rj-muster',
    notes:
      'Use Rajasthan state-government jurisdiction and the current applicability decision.',
    verifiedOn: '2026-09-14',
    effectiveFrom: '2026-08-12',
    applicability: 'REVIEW_REQUIRED',
    generation: 'REFERENCE_ONLY',
  },
  {
    id: 'rj--wages-2019--rajasthan-wages-2026--vii--rjw',
    jurisdiction: 'RJ',
    actCode: 'WAGES_2019',
    rulesCode: 'RAJASTHAN_WAGES_2026',
    formNumber: 'VII',
    title: 'Wage slip',
    ruleReference: 'Rule 43',
    kind: 'WAGE_SLIP',
    sourceId: 'rjw',
    sourceStatus: 'FINAL',
    sourcePage: 26,
    layoutId: 'rj-slip',
    notes:
      'Use Rajasthan state-government jurisdiction and the current applicability decision.',
    verifiedOn: '2026-09-14',
    effectiveFrom: '2026-08-12',
    applicability: 'REVIEW_REQUIRED',
    generation: 'REFERENCE_ONLY',
  },
  {
    id: 'central--wages-2019--central-wages-2026--i--cw',
    jurisdiction: 'CENTRAL',
    actCode: 'WAGES_2019',
    rulesCode: 'CENTRAL_WAGES_2026',
    formNumber: 'I',
    title: 'Employee register',
    ruleReference: 'Rule 51(1)(i)',
    kind: 'REGISTER',
    sourceId: 'cw',
    sourceStatus: 'FINAL',
    sourcePage: 53,
    layoutId: 'wages-employee',
    notes: 'Check appropriate-government jurisdiction before use.',
    verifiedOn: '2026-09-14',
    effectiveFrom: '2026-05-08',
    applicability: 'REVIEW_REQUIRED',
    generation: 'REFERENCE_ONLY',
  },
  {
    id: 'central--wages-2019--central-wages-2026--iv--cw',
    jurisdiction: 'CENTRAL',
    actCode: 'WAGES_2019',
    rulesCode: 'CENTRAL_WAGES_2026',
    formNumber: 'IV',
    title:
      'Wages, overtime, advances, fines and deductions for damage and loss',
    ruleReference: 'Rule 51(1)(ii)',
    kind: 'REGISTER',
    sourceId: 'cw',
    sourceStatus: 'FINAL',
    sourcePage: 56,
    layoutId: 'wages-combined',
    notes: 'Check appropriate-government jurisdiction before use.',
    verifiedOn: '2026-09-14',
    effectiveFrom: '2026-05-08',
    applicability: 'REVIEW_REQUIRED',
    generation: 'REFERENCE_ONLY',
  },
  {
    id: 'central--wages-2019--central-wages-2026--ix--cw',
    jurisdiction: 'CENTRAL',
    actCode: 'WAGES_2019',
    rulesCode: 'CENTRAL_WAGES_2026',
    formNumber: 'IX',
    title: 'Attendance register-cum-muster roll',
    ruleReference: 'Rule 51(1)(iii)',
    kind: 'REGISTER',
    sourceId: 'cw',
    sourceStatus: 'FINAL',
    sourcePage: 60,
    layoutId: 'wages-attendance',
    notes: 'Check appropriate-government jurisdiction before use.',
    verifiedOn: '2026-09-14',
    effectiveFrom: '2026-05-08',
    applicability: 'REVIEW_REQUIRED',
    generation: 'REFERENCE_ONLY',
  },
  {
    id: 'central--wages-2019--central-wages-2026--v--cw',
    jurisdiction: 'CENTRAL',
    actCode: 'WAGES_2019',
    rulesCode: 'CENTRAL_WAGES_2026',
    formNumber: 'V',
    title: 'Wage slip',
    ruleReference: 'Rule 52',
    kind: 'WAGE_SLIP',
    sourceId: 'cw',
    sourceStatus: 'FINAL',
    sourcePage: 57,
    layoutId: 'wages-slip',
    notes: 'Check appropriate-government jurisdiction before use.',
    verifiedOn: '2026-09-14',
    effectiveFrom: '2026-05-08',
    applicability: 'REVIEW_REQUIRED',
    generation: 'REFERENCE_ONLY',
  },
  {
    id: 'ap--wages-2019--ap-wages-2026--i--apw',
    jurisdiction: 'AP',
    actCode: 'WAGES_2019',
    rulesCode: 'AP_WAGES_2026',
    formNumber: 'I',
    title: 'Employee register',
    ruleReference: 'Rule 42(1)(i)',
    kind: 'REGISTER',
    sourceId: 'apw',
    sourceStatus: 'FINAL',
    sourcePage: 15,
    layoutId: 'wages-employee',
    notes: 'Check appropriate-government jurisdiction before use.',
    verifiedOn: '2026-09-14',
    effectiveFrom: '2026-06-29',
    applicability: 'REVIEW_REQUIRED',
    generation: 'REFERENCE_ONLY',
  },
  {
    id: 'ap--wages-2019--ap-wages-2026--iv--apw',
    jurisdiction: 'AP',
    actCode: 'WAGES_2019',
    rulesCode: 'AP_WAGES_2026',
    formNumber: 'IV',
    title:
      'Wages, overtime, advances, fines and deductions for damage and loss',
    ruleReference: 'Rule 42(1)(ii)',
    kind: 'REGISTER',
    sourceId: 'apw',
    sourceStatus: 'FINAL',
    sourcePage: 21,
    layoutId: 'wages-combined',
    notes: 'Check appropriate-government jurisdiction before use.',
    verifiedOn: '2026-09-14',
    effectiveFrom: '2026-06-29',
    applicability: 'REVIEW_REQUIRED',
    generation: 'REFERENCE_ONLY',
  },
  {
    id: 'ap--wages-2019--ap-wages-2026--ix--apw',
    jurisdiction: 'AP',
    actCode: 'WAGES_2019',
    rulesCode: 'AP_WAGES_2026',
    formNumber: 'IX',
    title: 'Attendance register-cum-muster roll',
    ruleReference: 'Rule 42(1)(iii)',
    kind: 'REGISTER',
    sourceId: 'apw',
    sourceStatus: 'FINAL',
    sourcePage: 30,
    layoutId: 'wages-attendance',
    notes: 'Check appropriate-government jurisdiction before use.',
    verifiedOn: '2026-09-14',
    effectiveFrom: '2026-06-29',
    applicability: 'REVIEW_REQUIRED',
    generation: 'REFERENCE_ONLY',
  },
  {
    id: 'ap--wages-2019--ap-wages-2026--v--apw',
    jurisdiction: 'AP',
    actCode: 'WAGES_2019',
    rulesCode: 'AP_WAGES_2026',
    formNumber: 'V',
    title: 'Wage slip',
    ruleReference: 'Rule 43',
    kind: 'WAGE_SLIP',
    sourceId: 'apw',
    sourceStatus: 'FINAL',
    sourcePage: 23,
    layoutId: 'wages-slip',
    notes: 'Check appropriate-government jurisdiction before use.',
    verifiedOn: '2026-09-14',
    effectiveFrom: '2026-06-29',
    applicability: 'REVIEW_REQUIRED',
    generation: 'REFERENCE_ONLY',
  },
  {
    id: 'central--osh-2020--central-osh-2026--v--osh',
    jurisdiction: 'CENTRAL',
    actCode: 'OSH_2020',
    rulesCode: 'CENTRAL_OSH_2026',
    formNumber: 'V',
    title: 'Register of establishments',
    ruleReference: 'Rule 3(9)',
    kind: 'AUTHORITY_REGISTER',
    sourceId: 'osh',
    sourceStatus: 'FINAL',
    sourcePage: 251,
    layoutId: null,
    notes:
      'Maintained by the registering authority; not an employer payroll register.',
    verifiedOn: '2026-09-14',
    effectiveFrom: '2026-05-08',
    applicability: 'REVIEW_REQUIRED',
    generation: 'REFERENCE_ONLY',
  },
  {
    id: 'central--osh-2020--central-osh-2026--xi--osh',
    jurisdiction: 'CENTRAL',
    actCode: 'OSH_2020',
    rulesCode: 'CENTRAL_OSH_2026',
    formNumber: 'XI',
    title: 'Notice of accident or dangerous occurrence',
    ruleReference: 'Rule 7(1) and 7(2)',
    kind: 'NOTICE',
    sourceId: 'osh',
    sourceStatus: 'FINAL',
    sourcePage: 273,
    layoutId: null,
    notes: 'Prescribed source retained; data population is not enabled.',
    verifiedOn: '2026-09-14',
    effectiveFrom: '2026-05-08',
    applicability: 'REVIEW_REQUIRED',
    generation: 'REFERENCE_ONLY',
  },
  {
    id: 'central--osh-2020--central-osh-2026--xii--osh',
    jurisdiction: 'CENTRAL',
    actCode: 'OSH_2020',
    rulesCode: 'CENTRAL_OSH_2026',
    formNumber: 'XII',
    title: 'Notice of periods of work',
    ruleReference: 'Rule 71',
    kind: 'NOTICE',
    sourceId: 'osh',
    sourceStatus: 'FINAL',
    sourcePage: 280,
    layoutId: null,
    notes: 'Prescribed source retained; data population is not enabled.',
    verifiedOn: '2026-09-14',
    effectiveFrom: '2026-05-08',
    applicability: 'REVIEW_REQUIRED',
    generation: 'REFERENCE_ONLY',
  },
  {
    id: 'central--osh-2020--central-osh-2026--xiii--osh',
    jurisdiction: 'CENTRAL',
    actCode: 'OSH_2020',
    rulesCode: 'CENTRAL_OSH_2026',
    formNumber: 'XIII',
    title: 'Employee register',
    ruleReference: 'Rule 72(1)(i)',
    kind: 'REGISTER',
    sourceId: 'osh',
    sourceStatus: 'FINAL',
    sourcePage: 281,
    layoutId: 'osh-employee',
    notes: 'Prescribed source retained; data population is not enabled.',
    verifiedOn: '2026-09-14',
    effectiveFrom: '2026-05-08',
    applicability: 'REVIEW_REQUIRED',
    generation: 'REFERENCE_ONLY',
  },
  {
    id: 'central--osh-2020--central-osh-2026--xiv--osh',
    jurisdiction: 'CENTRAL',
    actCode: 'OSH_2020',
    rulesCode: 'CENTRAL_OSH_2026',
    formNumber: 'XIV',
    title: 'Attendance register-cum-muster roll',
    ruleReference: 'Rule 72(1)(ii)',
    kind: 'REGISTER',
    sourceId: 'osh',
    sourceStatus: 'FINAL',
    sourcePage: 283,
    layoutId: 'osh-attendance',
    notes: 'Prescribed source retained; data population is not enabled.',
    verifiedOn: '2026-09-14',
    effectiveFrom: '2026-05-08',
    applicability: 'REVIEW_REQUIRED',
    generation: 'REFERENCE_ONLY',
  },
  {
    id: 'central--osh-2020--central-osh-2026--xv--osh',
    jurisdiction: 'CENTRAL',
    actCode: 'OSH_2020',
    rulesCode: 'CENTRAL_OSH_2026',
    formNumber: 'XV',
    title: 'Wages, overtime and deductions',
    ruleReference: 'Rule 72(1)(iii)',
    kind: 'REGISTER',
    sourceId: 'osh',
    sourceStatus: 'FINAL',
    sourcePage: 284,
    layoutId: 'osh-wages',
    notes: 'Prescribed source retained; data population is not enabled.',
    verifiedOn: '2026-09-14',
    effectiveFrom: '2026-05-08',
    applicability: 'REVIEW_REQUIRED',
    generation: 'REFERENCE_ONLY',
  },
  {
    id: 'central--osh-2020--central-osh-2026--xvi--osh',
    jurisdiction: 'CENTRAL',
    actCode: 'OSH_2020',
    rulesCode: 'CENTRAL_OSH_2026',
    formNumber: 'XVI',
    title: 'Wage slip',
    ruleReference: 'Rule 72(2)',
    kind: 'WAGE_SLIP',
    sourceId: 'osh',
    sourceStatus: 'FINAL',
    sourcePage: 286,
    layoutId: 'osh-slip',
    notes: 'Prescribed source retained; data population is not enabled.',
    verifiedOn: '2026-09-14',
    effectiveFrom: '2026-05-08',
    applicability: 'REVIEW_REQUIRED',
    generation: 'REFERENCE_ONLY',
  },
  {
    id: 'central--osh-2020--central-osh-2026--xvii--osh',
    jurisdiction: 'CENTRAL',
    actCode: 'OSH_2020',
    rulesCode: 'CENTRAL_OSH_2026',
    formNumber: 'XVII',
    title: 'Annual return',
    ruleReference: 'Rule 72(5)',
    kind: 'RETURN',
    sourceId: 'osh',
    sourceStatus: 'FINAL',
    sourcePage: 287,
    layoutId: null,
    notes: 'Prescribed source retained; data population is not enabled.',
    verifiedOn: '2026-09-14',
    effectiveFrom: '2026-05-08',
    applicability: 'REVIEW_REQUIRED',
    generation: 'REFERENCE_ONLY',
  },
  {
    id: 'central--osh-2020--central-osh-2026--xviii--osh',
    jurisdiction: 'CENTRAL',
    actCode: 'OSH_2020',
    rulesCode: 'CENTRAL_OSH_2026',
    formNumber: 'XVIII',
    title: 'Contractor half-yearly return',
    ruleReference: 'Rule 72(5) and 98(7)',
    kind: 'RETURN',
    sourceId: 'osh',
    sourceStatus: 'FINAL',
    sourcePage: 303,
    layoutId: null,
    notes: 'Prescribed source retained; data population is not enabled.',
    verifiedOn: '2026-09-14',
    effectiveFrom: '2026-05-08',
    applicability: 'REVIEW_REQUIRED',
    generation: 'REFERENCE_ONLY',
  },
  {
    id: 'central--osh-2020--central-osh-2026--xix--osh',
    jurisdiction: 'CENTRAL',
    actCode: 'OSH_2020',
    rulesCode: 'CENTRAL_OSH_2026',
    formNumber: 'XIX',
    title: 'Accidents and dangerous occurrences',
    ruleReference: 'Rule 75',
    kind: 'REGISTER',
    sourceId: 'osh',
    sourceStatus: 'FINAL',
    sourcePage: 304,
    layoutId: 'osh-accident',
    notes: 'Prescribed source retained; data population is not enabled.',
    verifiedOn: '2026-09-14',
    effectiveFrom: '2026-05-08',
    applicability: 'REVIEW_REQUIRED',
    generation: 'REFERENCE_ONLY',
  },
  {
    id: 'central--osh-2020--central-osh-2026--xx--osh',
    jurisdiction: 'CENTRAL',
    actCode: 'OSH_2020',
    rulesCode: 'CENTRAL_OSH_2026',
    formNumber: 'XX',
    title: 'Leave with wages',
    ruleReference: 'Rule 76',
    kind: 'REGISTER',
    sourceId: 'osh',
    sourceStatus: 'FINAL',
    sourcePage: 305,
    layoutId: 'osh-leave',
    notes: 'Prescribed source retained; data population is not enabled.',
    verifiedOn: '2026-09-14',
    effectiveFrom: '2026-05-08',
    applicability: 'REVIEW_REQUIRED',
    generation: 'REFERENCE_ONLY',
  },
  {
    id: 'central--osh-2020--central-osh-2026--xxiii--osh',
    jurisdiction: 'CENTRAL',
    actCode: 'OSH_2020',
    rulesCode: 'CENTRAL_OSH_2026',
    formNumber: 'XXIII',
    title: 'Experience certificate of contract labour',
    ruleReference: 'Rule 100',
    kind: 'CERTIFICATE',
    sourceId: 'osh',
    sourceStatus: 'FINAL',
    sourcePage: 310,
    layoutId: null,
    notes: 'Prescribed source retained; data population is not enabled.',
    verifiedOn: '2026-09-14',
    effectiveFrom: '2026-05-08',
    applicability: 'REVIEW_REQUIRED',
    generation: 'REFERENCE_ONLY',
  },
  {
    id: 'central--social-security-2020--central-ss-2026--xxii--ss',
    jurisdiction: 'CENTRAL',
    actCode: 'SOCIAL_SECURITY_2020',
    rulesCode: 'CENTRAL_SS_2026',
    formNumber: 'XXII',
    title: 'Women employees register',
    ruleReference: 'Rule 53(1)(a)',
    kind: 'REGISTER',
    sourceId: 'ss',
    sourceStatus: 'FINAL',
    sourcePage: 232,
    layoutId: null,
    notes:
      'Maternity-related event records require authorised HR input. Rule 53 also recognises common Wages/OSH registers; avoid duplicate payroll records.',
    verifiedOn: '2026-09-14',
    effectiveFrom: '2026-05-08',
    applicability: 'REVIEW_REQUIRED',
    generation: 'REFERENCE_ONLY',
  },
  {
    id: 'central--ir-2020--central-ir-2026--iii--ir',
    jurisdiction: 'CENTRAL',
    actCode: 'IR_2020',
    rulesCode: 'CENTRAL_IR_2026',
    formNumber: 'III',
    title: 'Register of standing orders',
    ruleReference: 'Rule 17',
    kind: 'AUTHORITY_REGISTER',
    sourceId: 'ir',
    sourceStatus: 'FINAL',
    sourcePage: null,
    layoutId: null,
    notes:
      'Maintained by the certifying officer, not generated as an employer payroll register.',
    verifiedOn: '2026-09-14',
    effectiveFrom: '2026-05-08',
    applicability: 'REVIEW_REQUIRED',
    generation: 'REFERENCE_ONLY',
  },
  {
    id: 'ts--multi-act--ts-integrated-2019--ii---iii--tsi',
    jurisdiction: 'TS',
    actCode: 'MULTI_ACT',
    rulesCode: 'TS_INTEGRATED_2019',
    formNumber: 'II + III',
    title: 'Integrated register (both forms together)',
    ruleReference: 'G.O.Ms.No.6, paragraphs 3–4',
    kind: 'REGISTER',
    sourceId: 'tsi',
    sourceStatus: 'EXISTING_RULES',
    sourcePage: 12,
    layoutId: 'ts-integrated',
    notes:
      'Both parts are required. Review current Code transition before operational use.',
    verifiedOn: '2026-09-14',
    effectiveFrom: null,
    applicability: 'REVIEW_REQUIRED',
    generation: 'REFERENCE_ONLY',
  },
  {
    id: 'ts--multi-act--ts-integrated-2019--i--tsi',
    jurisdiction: 'TS',
    actCode: 'MULTI_ACT',
    rulesCode: 'TS_INTEGRATED_2019',
    formNumber: 'I',
    title: 'Common annual return',
    ruleReference: 'G.O.Ms.No.6, paragraph 4',
    kind: 'RETURN',
    sourceId: 'tsi',
    sourceStatus: 'EXISTING_RULES',
    sourcePage: 4,
    layoutId: null,
    notes: 'Annual return, not a monthly register.',
    verifiedOn: '2026-09-14',
    effectiveFrom: null,
    applicability: 'REVIEW_REQUIRED',
    generation: 'REFERENCE_ONLY',
  },
  {
    id: 'mh--shops-2017--mh-shops-2018--q--mh',
    jurisdiction: 'MH',
    actCode: 'SHOPS_2017',
    rulesCode: 'MH_SHOPS_2018',
    formNumber: 'Q',
    title: 'Muster-roll cum wage register',
    ruleReference: 'Rule 26(1)',
    kind: 'REGISTER',
    sourceId: 'mh',
    sourceStatus: 'EXISTING_RULES',
    sourcePage: 90,
    layoutId: 'mh-shops-q',
    notes:
      'State Shops Act format; do not replace with a CLRA form carrying the same title.',
    verifiedOn: '2026-09-14',
    effectiveFrom: null,
    applicability: 'REVIEW_REQUIRED',
    generation: 'REFERENCE_ONLY',
  },
  {
    id: 'tn--factories-1948--tn-factories-1950-amend-2021--12--tn',
    jurisdiction: 'TN',
    actCode: 'FACTORIES_1948',
    rulesCode: 'TN_FACTORIES_1950_AMEND_2021',
    formNumber: '12',
    title: 'Adult workers and young persons',
    ruleReference: 'Rules 80 and 86',
    kind: 'REGISTER',
    sourceId: 'tn',
    sourceStatus: 'EXISTING_RULES',
    sourcePage: 3,
    layoutId: null,
    notes: '2021 amendment source; current Code transition requires review.',
    verifiedOn: '2026-09-14',
    effectiveFrom: null,
    applicability: 'REVIEW_REQUIRED',
    generation: 'REFERENCE_ONLY',
  },
  {
    id: 'tn--factories-1948--tn-factories-1950-amend-2021--15--tn',
    jurisdiction: 'TN',
    actCode: 'FACTORIES_1948',
    rulesCode: 'TN_FACTORIES_1950_AMEND_2021',
    formNumber: '15',
    title: 'Leave with wages',
    ruleReference: 'Rules 87 and 88',
    kind: 'REGISTER',
    sourceId: 'tn',
    sourceStatus: 'EXISTING_RULES',
    sourcePage: 4,
    layoutId: null,
    notes: '2021 amendment source; current Code transition requires review.',
    verifiedOn: '2026-09-14',
    effectiveFrom: null,
    applicability: 'REVIEW_REQUIRED',
    generation: 'REFERENCE_ONLY',
  },
  {
    id: 'tn--factories-1948--tn-factories-1950-amend-2021--25--tn',
    jurisdiction: 'TN',
    actCode: 'FACTORIES_1948',
    rulesCode: 'TN_FACTORIES_1950_AMEND_2021',
    formNumber: '25',
    title: 'Muster roll',
    ruleReference: 'Rule 103',
    kind: 'REGISTER',
    sourceId: 'tn',
    sourceStatus: 'EXISTING_RULES',
    sourcePage: 5,
    layoutId: null,
    notes: '2021 amendment source; current Code transition requires review.',
    verifiedOn: '2026-09-14',
    effectiveFrom: null,
    applicability: 'REVIEW_REQUIRED',
    generation: 'REFERENCE_ONLY',
  },
  {
    id: 'central--clra-1970--central-clra-1971--xii--clra',
    jurisdiction: 'CENTRAL',
    actCode: 'CLRA_1970',
    rulesCode: 'CENTRAL_CLRA_1971',
    formNumber: 'XII',
    title: 'Register of contractors',
    ruleReference: 'Rule 74',
    kind: 'REGISTER',
    sourceId: 'clra',
    sourceStatus: 'LEGACY',
    sourcePage: null,
    layoutId: 'clra-xii',
    notes:
      'Historical format; central 2026 OSH rules supersede these rules subject to savings.',
    verifiedOn: '2026-09-14',
    effectiveFrom: null,
    applicability: 'REVIEW_REQUIRED',
    generation: 'REFERENCE_ONLY',
  },
  {
    id: 'central--clra-1970--central-clra-1971--xiii--clra',
    jurisdiction: 'CENTRAL',
    actCode: 'CLRA_1970',
    rulesCode: 'CENTRAL_CLRA_1971',
    formNumber: 'XIII',
    title: 'Workmen employed by contractor',
    ruleReference: 'Rule 75',
    kind: 'REGISTER',
    sourceId: 'clra',
    sourceStatus: 'LEGACY',
    sourcePage: null,
    layoutId: 'clra-xiii',
    notes:
      'Historical format; central 2026 OSH rules supersede these rules subject to savings.',
    verifiedOn: '2026-09-14',
    effectiveFrom: null,
    applicability: 'REVIEW_REQUIRED',
    generation: 'REFERENCE_ONLY',
  },
  {
    id: 'central--clra-1970--central-clra-1971--xiv--clra',
    jurisdiction: 'CENTRAL',
    actCode: 'CLRA_1970',
    rulesCode: 'CENTRAL_CLRA_1971',
    formNumber: 'XIV',
    title: 'Employment card',
    ruleReference: 'Rule 76',
    kind: 'CARD',
    sourceId: 'clra',
    sourceStatus: 'LEGACY',
    sourcePage: null,
    layoutId: 'clra-xiv',
    notes:
      'Historical format; central 2026 OSH rules supersede these rules subject to savings.',
    verifiedOn: '2026-09-14',
    effectiveFrom: null,
    applicability: 'REVIEW_REQUIRED',
    generation: 'REFERENCE_ONLY',
  },
  {
    id: 'central--clra-1970--central-clra-1971--xv--clra',
    jurisdiction: 'CENTRAL',
    actCode: 'CLRA_1970',
    rulesCode: 'CENTRAL_CLRA_1971',
    formNumber: 'XV',
    title: 'Service certificate',
    ruleReference: 'Rule 77',
    kind: 'CERTIFICATE',
    sourceId: 'clra',
    sourceStatus: 'LEGACY',
    sourcePage: null,
    layoutId: 'clra-xv',
    notes:
      'Historical format; central 2026 OSH rules supersede these rules subject to savings.',
    verifiedOn: '2026-09-14',
    effectiveFrom: null,
    applicability: 'REVIEW_REQUIRED',
    generation: 'REFERENCE_ONLY',
  },
  {
    id: 'central--clra-1970--central-clra-1971--xvi--clra',
    jurisdiction: 'CENTRAL',
    actCode: 'CLRA_1970',
    rulesCode: 'CENTRAL_CLRA_1971',
    formNumber: 'XVI',
    title: 'Muster roll',
    ruleReference: 'Rule 78(1)(a)(i)',
    kind: 'REGISTER',
    sourceId: 'clra',
    sourceStatus: 'LEGACY',
    sourcePage: null,
    layoutId: 'clra-xvi',
    notes:
      'Historical format; central 2026 OSH rules supersede these rules subject to savings.',
    verifiedOn: '2026-09-14',
    effectiveFrom: null,
    applicability: 'REVIEW_REQUIRED',
    generation: 'REFERENCE_ONLY',
  },
  {
    id: 'central--clra-1970--central-clra-1971--xvii--clra',
    jurisdiction: 'CENTRAL',
    actCode: 'CLRA_1970',
    rulesCode: 'CENTRAL_CLRA_1971',
    formNumber: 'XVII',
    title: 'Register of wages',
    ruleReference: 'Rule 78(1)(a)(i)',
    kind: 'REGISTER',
    sourceId: 'clra',
    sourceStatus: 'LEGACY',
    sourcePage: null,
    layoutId: 'clra-xvii',
    notes:
      'Historical format; central 2026 OSH rules supersede these rules subject to savings.',
    verifiedOn: '2026-09-14',
    effectiveFrom: null,
    applicability: 'REVIEW_REQUIRED',
    generation: 'REFERENCE_ONLY',
  },
  {
    id: 'central--clra-1970--central-clra-1971--xviii--clra',
    jurisdiction: 'CENTRAL',
    actCode: 'CLRA_1970',
    rulesCode: 'CENTRAL_CLRA_1971',
    formNumber: 'XVIII',
    title: 'Wage-cum-muster roll',
    ruleReference: 'Rule 78(1)(a)(i)',
    kind: 'REGISTER',
    sourceId: 'clra',
    sourceStatus: 'LEGACY',
    sourcePage: null,
    layoutId: 'clra-xviii',
    notes:
      'Historical format; central 2026 OSH rules supersede these rules subject to savings.',
    verifiedOn: '2026-09-14',
    effectiveFrom: null,
    applicability: 'REVIEW_REQUIRED',
    generation: 'REFERENCE_ONLY',
  },
  {
    id: 'central--clra-1970--central-clra-1971--xix--clra',
    jurisdiction: 'CENTRAL',
    actCode: 'CLRA_1970',
    rulesCode: 'CENTRAL_CLRA_1971',
    formNumber: 'XIX',
    title: 'Wage slip',
    ruleReference: 'Rule 78(1)(b)',
    kind: 'WAGE_SLIP',
    sourceId: 'clra',
    sourceStatus: 'LEGACY',
    sourcePage: null,
    layoutId: 'clra-xix',
    notes:
      'Historical format; central 2026 OSH rules supersede these rules subject to savings.',
    verifiedOn: '2026-09-14',
    effectiveFrom: null,
    applicability: 'REVIEW_REQUIRED',
    generation: 'REFERENCE_ONLY',
  },
  {
    id: 'central--clra-1970--central-clra-1971--xx--clra',
    jurisdiction: 'CENTRAL',
    actCode: 'CLRA_1970',
    rulesCode: 'CENTRAL_CLRA_1971',
    formNumber: 'XX',
    title: 'Deductions for damage or loss',
    ruleReference: 'Rule 78(1)(a)(ii)',
    kind: 'REGISTER',
    sourceId: 'clra',
    sourceStatus: 'LEGACY',
    sourcePage: null,
    layoutId: 'clra-xx',
    notes:
      'Historical format; central 2026 OSH rules supersede these rules subject to savings.',
    verifiedOn: '2026-09-14',
    effectiveFrom: null,
    applicability: 'REVIEW_REQUIRED',
    generation: 'REFERENCE_ONLY',
  },
  {
    id: 'central--clra-1970--central-clra-1971--xxi--clra',
    jurisdiction: 'CENTRAL',
    actCode: 'CLRA_1970',
    rulesCode: 'CENTRAL_CLRA_1971',
    formNumber: 'XXI',
    title: 'Fines',
    ruleReference: 'Rule 78(1)(a)(ii)',
    kind: 'REGISTER',
    sourceId: 'clra',
    sourceStatus: 'LEGACY',
    sourcePage: null,
    layoutId: 'clra-xxi',
    notes:
      'Historical format; central 2026 OSH rules supersede these rules subject to savings.',
    verifiedOn: '2026-09-14',
    effectiveFrom: null,
    applicability: 'REVIEW_REQUIRED',
    generation: 'REFERENCE_ONLY',
  },
  {
    id: 'central--clra-1970--central-clra-1971--xxii--clra',
    jurisdiction: 'CENTRAL',
    actCode: 'CLRA_1970',
    rulesCode: 'CENTRAL_CLRA_1971',
    formNumber: 'XXII',
    title: 'Advances',
    ruleReference: 'Rule 78(1)(a)(ii)',
    kind: 'REGISTER',
    sourceId: 'clra',
    sourceStatus: 'LEGACY',
    sourcePage: null,
    layoutId: 'clra-xxii',
    notes:
      'Historical format; central 2026 OSH rules supersede these rules subject to savings.',
    verifiedOn: '2026-09-14',
    effectiveFrom: null,
    applicability: 'REVIEW_REQUIRED',
    generation: 'REFERENCE_ONLY',
  },
  {
    id: 'central--clra-1970--central-clra-1971--xxiii--clra',
    jurisdiction: 'CENTRAL',
    actCode: 'CLRA_1970',
    rulesCode: 'CENTRAL_CLRA_1971',
    formNumber: 'XXIII',
    title: 'Overtime',
    ruleReference: 'Rule 78(1)(a)(iii)',
    kind: 'REGISTER',
    sourceId: 'clra',
    sourceStatus: 'LEGACY',
    sourcePage: null,
    layoutId: 'clra-xxiii',
    notes:
      'Historical format; central 2026 OSH rules supersede these rules subject to savings.',
    verifiedOn: '2026-09-14',
    effectiveFrom: null,
    applicability: 'REVIEW_REQUIRED',
    generation: 'REFERENCE_ONLY',
  },
] as const;
