export const SERVICE_MODULE_CODES = [
  'CONTRACTOR_AUDIT',
  'CONTRACTOR_PORTAL',
  'CONTRACTOR_DOCUMENTS',
  'CONTRACTOR_ATTENDANCE',
  'CONTRACTOR_FACE_ATTENDANCE',
  'PAYROLL',
  'EMPLOYEE_COMPLIANCE',
  'EMPLOYEE_ATTENDANCE',
  'MOBILE_ATTENDANCE',
  'APPRAISAL',
] as const;

export type ServiceModuleCode = (typeof SERVICE_MODULE_CODES)[number];

export const FULL_SERVICE_PACKAGE = 'FULL_SERVICE';
export const CONTRACTOR_AUDIT_ONLY_PACKAGE = 'CONTRACTOR_AUDIT_ONLY';

export const PACKAGE_MODULES: Record<string, ServiceModuleCode[]> = {
  [FULL_SERVICE_PACKAGE]: [...SERVICE_MODULE_CODES],
  [CONTRACTOR_AUDIT_ONLY_PACKAGE]: [
    'CONTRACTOR_AUDIT',
    'CONTRACTOR_PORTAL',
    'CONTRACTOR_DOCUMENTS',
    'CONTRACTOR_ATTENDANCE',
    'CONTRACTOR_FACE_ATTENDANCE',
  ],
};

export const SERVICE_PACKAGE_OPTIONS = [
  {
    code: FULL_SERVICE_PACKAGE,
    label: 'Full Service',
    modules: PACKAGE_MODULES[FULL_SERVICE_PACKAGE],
  },
  {
    code: CONTRACTOR_AUDIT_ONLY_PACKAGE,
    label: 'Contractor Audit Only',
    modules: PACKAGE_MODULES[CONTRACTOR_AUDIT_ONLY_PACKAGE],
  },
];
